"""
Stage Describe - Object Description Generation Stage
=====================================================

Features:
1. Parse bounding box, location, rotation for each object from code
2. Generate detailed descriptions for each object based on image (what it is, appearance, material, color)
3. Define the overall room style

Usage:
    cd /Users/yangyixuan/SceneGen_Agent/agent_utils
    
    # Basic usage
    python stage5_describe.py --image /Users/yangyixuan/SceneGen_Agent/agent_input/test6.png --scene-code /Users/yangyixuan/SceneGen_Agent/agent_utils/pipeline_output/stage4/stage4_output.py
    
    # Use Memory
    python stage5_describe.py --image /path/to/image.png  # Auto-get code from Memory
    
    # Show Memory status
    python stage5_describe.py --status

Author: Auto-generated
"""

import os
import sys
import re
import json
import base64
import argparse
import ast
from typing import Dict, List, Any, Optional, Tuple
from dataclasses import dataclass, asdict

# Path setup
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, current_dir)
sys.path.insert(0, os.path.join(current_dir, "stage3"))

from stage3.core import LLMClient, PromptManager, extract_python_from_response
from memory import Memory
from langchain_core.messages import HumanMessage, SystemMessage


# ==============================================================================
# Data Structures
# ==============================================================================
@dataclass
class ObjectInfo:
    """Object information data structure"""
    name: str                     # Object name (from code)
    shape: str                    # Shape type (box/cylinder)
    location: Tuple[float, float, float]   # Location (x, y, z)
    dimensions: Tuple[float, float, float] # Dimensions (width, depth, height)
    rotation: Tuple[float, float, float]   # Rotation (rx, ry, rz) in radians
    rotation_degrees: Tuple[float, float, float]  # Rotation in degrees
    material_name: str            # Material name
    collection: str               # Collection/zone name
    
    # Descriptions generated by LLM
    description: str = ""         # Object description
    object_type: str = ""         # Object type (e.g., bed, chair, lamp)
    appearance: str = ""          # Appearance description
    material_description: str = ""  # Material description
    color_description: str = ""   # Color description
    
    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class RoomStyleInfo:
    """Room style information"""
    style_name: str               # Style name
    style_description: str        # Style description
    color_palette: List[str]      # Primary color list
    mood: str                     # Mood/atmosphere
    era: str                      # Era style
    keywords: List[str]           # Keywords
    
    def to_dict(self) -> dict:
        return asdict(self)


# ==============================================================================
# Code Parser
# ==============================================================================
class BlenderCodeParser:
    """Parse Blender Python code to extract object information.
    
    Handles:
    - Nested parentheses in location/dimension expressions
    - f-string names in for-loops (unrolls loops)
    - Variable names used as arguments in loops
    - bpy.data.collections.new() and create_collection() patterns
    - Dynamic SCENE_W/SCENE_D extraction from code
    """
    
    def __init__(self, code: str):
        self.code = code
        self.objects: List[ObjectInfo] = []
        self.materials: Dict[str, Any] = {}
        self.collections: Dict[str, str] = {}  # var_name -> collection_name
        self.eval_env: Dict[str, Any] = {}     # Variables for eval
        
    def parse(self) -> List[ObjectInfo]:
        """Parse code, return object list"""
        self._build_eval_env()
        self._parse_materials()
        self._parse_collections()
        self._parse_all_objects()
        return self.objects
    
    # ---------- Eval Environment ----------

    def _extract_scene_dim(self, var_name: str, default: float) -> float:
        """Extract a scalar like SCENE_W / SCENE_D from arbitrary assignment
        syntax in the parsed Blender code.

        Supports:
          * `SCENE_W = 6.5`
          * `SCENE_W: float = 6.5`
          * `SCENE_W, SCENE_D = 6.5, 5.5`           (tuple unpacking, common)
          * `SCENE_D, SCENE_W = 5.5, 6.5`           (any order)
          * `SCENE_W, SCENE_D, WALL_H = 6.5, 5.5, 2.7`

        Returns `default` when no recognizable assignment is found. We
        deliberately scan ALL matches and pick the FIRST plausible one (so
        that a later in-function re-assignment does not silently override
        the canonical value at the top of run_layout_engine).
        """
        # IMPORTANT: order matters. Tuple-unpacking MUST be checked first,
        # otherwise `SCENE_W, SCENE_D = 6.5, 5.5` would (wrongly) let a
        # naive single-var regex match `SCENE_D = 6.5` and assign 6.5 to
        # SCENE_D as well.

        # Pattern 1: tuple unpacking — find any line whose LHS is a
        # comma-separated list of identifiers and whose RHS is a comma-
        # separated list of numeric literals; then index by the position
        # of `var_name` on the LHS.
        tuple_pat = re.compile(
            r'^[ \t]*([A-Za-z_]\w*(?:\s*,\s*[A-Za-z_]\w*)+)\s*=\s*'
            r'((?:-?\d+(?:\.\d+)?)(?:\s*,\s*-?\d+(?:\.\d+)?)+)\s*$',
            re.MULTILINE,
        )
        for tm in tuple_pat.finditer(self.code):
            lhs_names = [n.strip() for n in tm.group(1).split(',')]
            rhs_vals = [v.strip() for v in tm.group(2).split(',')]
            if var_name in lhs_names and len(lhs_names) == len(rhs_vals):
                idx = lhs_names.index(var_name)
                try:
                    return float(rhs_vals[idx])
                except (TypeError, ValueError):
                    continue

        # Pattern 2: simple `SCENE_W = 6.5` (optionally with type hint),
        # but ONLY when `var_name` is the sole identifier on the LHS. We
        # enforce this by anchoring the match to the start of a line and
        # disallowing any other identifier between line-start and the
        # `=` sign.
        single_pat = re.compile(
            rf'^[ \t]*{re.escape(var_name)}\s*(?::\s*[A-Za-z_][\w\[\], ]*)?\s*=\s*'
            r'(-?\d+(?:\.\d+)?)\s*(?:#.*)?$',
            re.MULTILINE,
        )
        m = single_pat.search(self.code)
        if m:
            try:
                return float(m.group(1))
            except (TypeError, ValueError):
                pass

        return float(default)

    def _build_eval_env(self):
        """Build evaluation environment from code: SCENE_W, SCENE_D, to_world, etc."""
        import math

        # Extract SCENE_W / SCENE_D from code. We MUST handle three syntaxes
        # observed in Stage 3 / Stage 4 outputs, in order of preference:
        #
        #   1) Tuple unpacking (most common in current pipeline):
        #          SCENE_W, SCENE_D = 6.5, 5.5
        #   2) Single assignment:
        #          SCENE_W = 6.5
        #          SCENE_D = 5.5
        #   3) Reverse-order tuple unpacking (defensive):
        #          SCENE_D, SCENE_W = 5.5, 6.5
        #
        # The previous regex `SCENE_W\s*[=,]\s*([\d.]+)` SILENTLY failed on
        # form (1) — the comma matched fine but the next token "SCENE_D" is
        # not a digit, so the whole regex didn't match. The code then
        # fell back to the hard-coded default SCENE_W=8.5, which is how a
        # Stage 4 expression like `-SCENE_W/2 + 0.05` ended up evaluating to
        # -4.2 instead of the correct -3.2 for a 6.5 m wide kitchen.
        scene_w = self._extract_scene_dim('SCENE_W', default=8.5)
        scene_d = self._extract_scene_dim('SCENE_D', default=7.0)
        self.eval_env['SCENE_W'] = scene_w
        self.eval_env['SCENE_D'] = scene_d

        SW = self.eval_env['SCENE_W']
        SD = self.eval_env['SCENE_D']
        
        # Build to_world helper if present in code
        def to_world(x_norm, y_norm):
            return ((x_norm - 0.5) * SW, (0.5 - y_norm) * SD)
        
        self.eval_env['to_world'] = to_world
        self.eval_env['math'] = math
        self.eval_env['pi'] = math.pi
        self.eval_env['WALL_H'] = 2.8
        self.eval_env['WALL_T'] = 0.15

        # mathutils exists only inside Blender; Stage 3/4 lab code uses
        # mathutils.Vector / mathutils.Euler for island bench offsets.  A tiny
        # stub is enough for the parser eval passes (Z-yaw benches are common).
        class _Vec:
            __slots__ = ("x", "y", "z")

            def __init__(self, xyz):
                t = tuple(xyz)
                if len(t) >= 3:
                    self.x, self.y, self.z = float(t[0]), float(t[1]), float(t[2])
                else:
                    self.x = self.y = self.z = 0.0

        class _Mat3:
            __slots__ = ("m",)

            def __init__(self, rows):
                self.m = rows

            def __matmul__(self, other):
                if isinstance(other, _Vec):
                    m = self.m
                    x = m[0][0] * other.x + m[0][1] * other.y + m[0][2] * other.z
                    y = m[1][0] * other.x + m[1][1] * other.y + m[1][2] * other.z
                    z = m[2][0] * other.x + m[2][1] * other.y + m[2][2] * other.z
                    return _Vec((x, y, z))
                return NotImplemented

        class _Euler:
            def __init__(self, angles, order="XYZ"):
                self.angles = tuple(float(a) for a in angles)
                self.order = order

            def to_matrix(self):
                rx, ry, rz = self.angles[0], self.angles[1], self.angles[2]
                if abs(rx) < 1e-9 and abs(ry) < 1e-9:
                    c, s = math.cos(rz), math.sin(rz)
                    return _Mat3(
                        [[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]]
                    )
                cx, sx = math.cos(rx), math.sin(rx)
                cy, sy = math.cos(ry), math.sin(ry)
                cz, sz = math.cos(rz), math.sin(rz)
                rx_m = [[1, 0, 0], [0, cx, -sx], [0, sx, cx]]
                ry_m = [[cy, 0, sy], [0, 1, 0], [-sy, 0, cy]]
                rz_m = [[cz, -sz, 0], [sz, cz, 0], [0, 0, 1]]

                def mm(a, b):
                    return [
                        [
                            sum(a[i][k] * b[k][j] for k in range(3))
                            for j in range(3)
                        ]
                        for i in range(3)
                    ]

                return _Mat3(mm(rz_m, mm(ry_m, rx_m)))

        class _Mathutils:
            Vector = staticmethod(lambda t: _Vec(t))
            Euler = _Euler

        self.eval_env["mathutils"] = _Mathutils()
        
        # Extract variable assignments like loc_desk = to_world(0.38, 0.62)
        var_pattern = r'(\w+)\s*=\s*to_world\s*\(\s*([\d.]+)\s*,\s*([\d.]+)\s*\)'
        for m in re.finditer(var_pattern, self.code):
            vname = m.group(1)
            x_n, y_n = float(m.group(2)), float(m.group(3))
            self.eval_env[vname] = to_world(x_n, y_n)
        
        # Tuple variable assignments are resolved inside the multi-pass loop below
        
        # Extract scalar and multi-variable assignments with multi-pass
        # resolution to handle dependency chains like:
        #   bed_d = 2.1
        #   bed_y = SCENE_D/2 - bed_d/2   (depends on bed_d and SCENE_D)
        safe_builtins = {"abs": abs, "min": min, "max": max, "round": round, 
                         "int": int, "float": float, "len": len}
        
        scalar_pattern = r'^ {4}(\w+)\s*=\s*([^=\n][^\n]*?)\s*$'
        multi_assign_pattern = r'^ {4}(\w+(?:\s*,\s*\w+)+)\s*=\s*([^=\n][^\n]*?)\s*$'
        
        # Collect all candidate assignments first (preserving code order)
        scalar_candidates = []
        for m in re.finditer(scalar_pattern, self.code, re.MULTILINE):
            vname = m.group(1)
            expr = BlenderCodeParser._strip_trailing_comment_outside_strings(
                m.group(2).strip()
            ).strip()
            if expr.startswith(('create_', 'bpy.', '"', "'", '[', '{')):
                continue
            if '=' in expr and not any(op in expr for op in ['==', '!=', '<=', '>=']):
                continue
            scalar_candidates.append((vname, expr))
        
        multi_candidates = []
        for m in re.finditer(multi_assign_pattern, self.code, re.MULTILINE):
            names = [n.strip() for n in m.group(1).split(',')]
            vals_str = BlenderCodeParser._strip_trailing_comment_outside_strings(
                m.group(2).strip()
            ).strip()
            multi_candidates.append((names, vals_str))
        
        tuple_candidates = []
        tuple_var_pattern = r'(\w+)\s*=\s*\(([^=][^;]*?)\)\s*$'
        for m in re.finditer(tuple_var_pattern, self.code, re.MULTILINE):
            inner = BlenderCodeParser._strip_trailing_comment_outside_strings(
                m.group(2).strip()
            ).strip()
            tuple_candidates.append((m.group(1), inner))
        
        MAX_PASSES = 5
        for _ in range(MAX_PASSES):
            resolved_any = False
            
            for vname, expr in scalar_candidates:
                if vname in self.eval_env:
                    continue
                try:
                    val = eval(expr, {"__builtins__": safe_builtins}, self.eval_env)
                    self.eval_env[vname] = val
                    resolved_any = True
                except:
                    pass
            
            for names, vals_str in multi_candidates:
                if any(n in self.eval_env for n in names):
                    continue
                try:
                    vals = eval(f'({vals_str},)' if ',' not in vals_str else f'({vals_str})',
                               {"__builtins__": safe_builtins}, self.eval_env)
                    if len(vals) == len(names):
                        for n, v in zip(names, vals):
                            self.eval_env[n] = v
                        resolved_any = True
                except:
                    pass
            
            for vname, inner_expr in tuple_candidates:
                if vname in self.eval_env:
                    continue
                try:
                    val = eval(f'({inner_expr})', {"__builtins__": safe_builtins}, self.eval_env)
                    self.eval_env[vname] = val
                    resolved_any = True
                except:
                    pass
            
            if not resolved_any:
                break

        self._resolve_rotmat_vector_offsets(safe_builtins)
    
    def _resolve_rotmat_vector_offsets(self, safe_builtins: dict) -> None:
        """Resolve `post_off_X = rot_mat @ mathutils.Vector((...))` even when the
        Vector(...) call spans multiple lines (scalar_pattern only sees single-line
        assignments).  Without this, `bench_cx + post_off_L.x` evaluates to garbage
        and island posts collapse to the origin in describe / Stage 8."""
        if "rot_mat" not in self.eval_env or "mathutils" not in self.eval_env:
            return
        for m in re.finditer(
            r"^ {4}(\w+)\s*=\s*rot_mat\s*@\s*mathutils\.Vector",
            self.code,
            re.MULTILINE,
        ):
            vname = m.group(1)
            if vname in self.eval_env:
                continue
            tail = self.code[m.end() :]
            p0 = tail.find("(")
            if p0 < 0:
                continue
            abs_open = m.end() + p0
            vec_call = self._extract_balanced_paren(self.code, abs_open)
            if not vec_call or len(vec_call) < 2:
                continue
            inner = vec_call[1:-1].strip()
            if inner.startswith("(") and inner.endswith(")"):
                inner = inner[1:-1].strip()
            inner = self._strip_trailing_comment_outside_strings(inner).strip()
            try:
                tup = eval(
                    f"({inner})",
                    {"__builtins__": safe_builtins},
                    self.eval_env,
                )
                vec = self.eval_env["mathutils"].Vector(tup)
                self.eval_env[vname] = self.eval_env["rot_mat"] @ vec
            except Exception:
                pass
    
    # ---------- Materials ----------
    
    def _parse_materials(self):
        """Parse material definitions"""
        pattern = r'(\w+)\s*=\s*create_material\s*\(\s*["\']([^"\']+)["\']\s*,\s*\(([^)]+)\)'
        for match in re.finditer(pattern, self.code):
            var_name = match.group(1)
            mat_name = match.group(2)
            color_str = match.group(3)
            try:
                color_values = [float(x.strip()) for x in color_str.split(',')]
                self.materials[var_name] = {
                    'name': mat_name,
                    'color': color_values[:3] if len(color_values) >= 3 else [0.5, 0.5, 0.5]
                }
            except:
                self.materials[var_name] = {'name': mat_name, 'color': [0.5, 0.5, 0.5]}
    
    # ---------- Collections ----------
    
    def _parse_collections(self):
        """Parse collection definitions (both styles)"""
        # Style 1: coll = create_collection("Name")
        for m in re.finditer(r'(\w+)\s*=\s*create_collection\s*\(\s*["\']([^"\']+)', self.code):
            self.collections[m.group(1)] = m.group(2)
        # Style 2: coll = bpy.data.collections.new("Name")
        for m in re.finditer(r'(\w+)\s*=\s*bpy\.data\.collections\.new\s*\(\s*["\']([^"\']+)', self.code):
            self.collections[m.group(1)] = m.group(2)
    
    # ---------- Balanced Parenthesis Extraction ----------
    
    @staticmethod
    def _extract_balanced_paren(text: str, start: int) -> Optional[str]:
        """Extract balanced parenthesized expression starting at text[start]='('."""
        if start >= len(text) or text[start] != '(':
            return None
        depth = 0
        for i in range(start, len(text)):
            if text[i] == '(':
                depth += 1
            elif text[i] == ')':
                depth -= 1
                if depth == 0:
                    return text[start:i + 1]
        return None
    
    @staticmethod
    def _strip_trailing_comment_outside_strings(line: str) -> str:
        """Remove a Python `# ...` comment from one source line, only outside quotes.

        Stage 3/4 often appends inline comments after tuple closings, e.g.
        `(bench_cx, bench_cy, 0.45),  # H_work / 2`.  `_collect_full_call` joins
        continuation lines with spaces; if the `#` is kept, everything after it on
        that merged line is treated as comment and the next argument (dimensions)
        is lost — dimensions become (0,0,0) and Stage 8 geometry hallucinates.
        """
        in_str = False
        quote_ch = None
        escape = False
        i = 0
        while i < len(line):
            ch = line[i]
            if escape:
                escape = False
                i += 1
                continue
            if ch == "\\" and in_str:
                escape = True
                i += 1
                continue
            if not in_str:
                if ch in ('"', "'"):
                    in_str = True
                    quote_ch = ch
                elif ch == "#":
                    return line[:i].rstrip()
            else:
                if ch == quote_ch:
                    in_str = False
                    quote_ch = None
            i += 1
        return line

    @staticmethod
    def _split_top_level_args(s: str) -> List[str]:
        """Split by commas at top level only (not inside parens/brackets)."""
        args = []
        depth_paren = 0
        depth_bracket = 0
        current = []
        for ch in s:
            if ch == '(':
                depth_paren += 1
            elif ch == ')':
                depth_paren -= 1
            elif ch == '[':
                depth_bracket += 1
            elif ch == ']':
                depth_bracket -= 1
            elif ch == ',' and depth_paren == 0 and depth_bracket == 0:
                args.append(''.join(current).strip())
                current = []
                continue
            current.append(ch)
        if current:
            args.append(''.join(current).strip())
        return args
    
    # ---------- Object Parsing ----------
    
    @staticmethod
    def _collect_full_call(lines: List[str], start_idx: int) -> Tuple[str, int]:
        """Collect a full (possibly multi-line) function call starting at start_idx.
        Returns (full_call_str_stripped, end_idx)."""
        paren_depth = 0
        collected = []
        for j in range(start_idx, len(lines)):
            text = lines[j]
            cleaned = BlenderCodeParser._strip_trailing_comment_outside_strings(
                text.strip()
            )
            collected.append(cleaned)
            paren_depth += text.count('(') - text.count(')')
            if paren_depth <= 0:
                return ' '.join(collected), j
        return ' '.join(collected), len(lines) - 1
    
    def _parse_all_objects(self):
        """Parse ALL object creation calls including those in for-loops."""
        lines = self.code.split('\n')
        i = 0
        while i < len(lines):
            line = lines[i].strip()
            
            # Detect for-loop that contains create_box / create_cylinder
            if line.startswith('for ') and line.endswith(':'):
                loop_header = line
                loop_body_lines = []
                i += 1
                if i < len(lines):
                    base_indent = len(lines[i]) - len(lines[i].lstrip()) if lines[i].strip() else 0
                    while i < len(lines) and (not lines[i].strip() or (len(lines[i]) - len(lines[i].lstrip()) >= base_indent and lines[i].strip())):
                        loop_body_lines.append(lines[i])
                        i += 1
                        if i >= len(lines):
                            break
                
                body_text = '\n'.join(loop_body_lines)
                # Direct primitive creators — fast path.
                creates_directly = (
                    'create_box' in body_text
                    or 'create_cylinder' in body_text
                    or 'create_detailed_object' in body_text
                )
                # Indirect creators — the body calls a top-level helper
                # (e.g. ``add_chair``, ``make_dining_set``) whose body in
                # turn calls ``create_box``. Detect by name match against
                # ``_collect_helper_funcs()`` whose own body contains
                # primitive creators. Without this, ``for ... in
                # chair_positions.items(): add_chair(...)`` would silently
                # skip the loop and lose every chair.
                creates_via_helper = False
                if not creates_directly:
                    creators = self._helper_func_creator_names()
                    if creators:
                        import re as _re
                        for fn_name in creators:
                            if _re.search(rf"\b{_re.escape(fn_name)}\s*\(", body_text):
                                creates_via_helper = True
                                break
                if creates_directly or creates_via_helper:
                    self._unroll_loop(loop_header, loop_body_lines)
                continue
            
            # Direct create_box / create_cylinder calls (handle multi-line)
            if 'create_box(' in line or 'create_cylinder(' in line:
                full_call, end_idx = self._collect_full_call(lines, i)
                obj = self._parse_single_call(full_call)
                if obj and not self._is_architectural(obj.name):
                    self.objects.append(obj)
                i = end_idx
            
            i += 1
    
    def _parse_single_call(self, line: str) -> Optional[ObjectInfo]:
        """Parse a single create_box/create_cylinder call from a line."""
        line = line.strip()
        
        # Determine shape
        if 'create_box(' in line:
            shape = 'box'
            func_start = line.index('create_box(') + len('create_box(')
        elif 'create_cylinder(' in line:
            shape = 'cylinder'
            func_start = line.index('create_cylinder(') + len('create_cylinder(')
        else:
            return None
        
        # Extract all arguments inside the outer parentheses
        # Find the opening paren of the function call
        call_start = line.index('create_box(') if shape == 'box' else line.index('create_cylinder(')
        paren_pos = line.index('(', call_start)
        full_args_str = self._extract_balanced_paren(line, paren_pos)
        if not full_args_str:
            return None
        
        # Strip outer parens to get inner content
        inner = full_args_str[1:-1].strip()
        
        # Split top-level arguments
        args = self._split_top_level_args(inner)
        if len(args) < 3:
            return None
        
        # arg[0] = name (string), arg[1] = location (tuple), arg[2] = dimensions (tuple)
        name = self._extract_string_value(args[0])
        if not name:
            return None
        
        location = self._safe_eval_tuple(args[1])
        dimensions = self._safe_eval_tuple(args[2])
        
        # Parse rotation/material/collection. Stage 3/4 code may pass these
        # either as keywords or as positional args:
        # create_box(name, loc, dims, bench_rot, mat_bench, coll_zone)
        rotation = (0.0, 0.0, 0.0)
        material_name = ""
        collection_name = "Scene"
        
        for idx, arg in enumerate(args[3:], start=3):
            arg = arg.strip()
            if arg.startswith('rotation=') or arg.startswith('rotation ='):
                rot_expr = arg.split('=', 1)[1].strip()
                rotation = self._safe_eval_tuple(rot_expr)
            elif arg.startswith('material=') or arg.startswith('material ='):
                mat_var = arg.split('=', 1)[1].strip()
                if mat_var in self.materials:
                    material_name = self.materials[mat_var]['name']
            elif arg.startswith('collection=') or arg.startswith('collection ='):
                col_var = arg.split('=', 1)[1].strip()
                if col_var in self.collections:
                    collection_name = self.collections[col_var]
            elif '=' not in arg:
                if idx == 3:
                    rotation = self._safe_eval_tuple(arg)
                elif idx == 4:
                    if arg in self.materials:
                        material_name = self.materials[arg]['name']
                elif idx == 5:
                    if arg in self.collections:
                        collection_name = self.collections[arg]
        
        import math
        rotation_degrees = tuple(round(r * 180 / math.pi, 1) for r in rotation)
        
        return ObjectInfo(
            name=name,
            shape=shape,
            location=location,
            dimensions=dimensions,
            rotation=rotation,
            rotation_degrees=rotation_degrees,
            material_name=material_name,
            collection=collection_name
        )
    
    def _collect_literal_iterables(self) -> Dict[str, Any]:
        """Walk the full AST and collect every ``name = <iterable>`` assignment
        as a potential iterable source for ``_unroll_loop``.

        We walk the whole tree (not just ``tree.body``) because real Stage 3/4
        scripts wrap everything in ``def run_layout_engine(): ...``, so the
        interesting assignments live inside a ``FunctionDef.body``.

        Two-pass strategy:

        **Pass 1** — ``ast.literal_eval`` on every Assign. Captures pure
        list / dict / tuple / set literals.  Cheap, safe, original behaviour.

        **Pass 2** — Helper-call rescue.  Some Stage 3/4 scripts emit::

            chair_positions = {
                "obj_002_Dining_Chair_North_Left": norm_to_world(0.46, 0.40, SCENE_W, SCENE_D),
                ...
            }

        The values are helper-function calls, not literal tuples, so
        ``ast.literal_eval`` rejects the **whole** dict and we lose every
        entry — including the chair names that downstream stages need.
        For each non-literal Assign whose RHS contains an ``ast.Call``,
        we re-run ``eval`` against a sandbox containing:

        - Pass-1 literals (so ``SCENE_W`` / ``table_dim`` resolve)
        - Top-level ``def`` helpers via ``_collect_helper_funcs`` (so
          ``norm_to_world`` / ``yaw_to_face`` etc. resolve)
        - ``math`` and ``__builtins__``

        Only iterable results (list / dict / tuple / set) are accepted, so
        ``mat_x = create_pbr_material(...)`` (which returns a Material or
        sentinel) does NOT poison ``out``.  Newly captured iterables are
        written back into the sandbox so chained references like
        ``positions = build_grid(SCENE_W); subset = positions[:4]`` resolve.

        Last-write-wins for duplicate names (matches Python semantics for
        the outermost surrounding scope, which is what loops typically
        iterate).
        """
        import math as _math

        out: Dict[str, Any] = {}
        try:
            tree = ast.parse(self.code)
        except SyntaxError:
            return out

        assigns: List[Tuple[str, ast.AST]] = []
        all_literals: Dict[str, Any] = {}  # scalars + iterables, for sandbox
        for node in ast.walk(tree):
            if not isinstance(node, ast.Assign):
                continue
            if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
                continue
            name = node.targets[0].id
            assigns.append((name, node.value))
            try:
                val = ast.literal_eval(node.value)
            except (ValueError, SyntaxError, TypeError):
                continue
            all_literals[name] = val
            if isinstance(val, (list, dict, tuple, set)):
                out[name] = val

        sandbox: Dict[str, Any] = dict(self.eval_env)
        sandbox.setdefault("math", _math)
        sandbox.setdefault("__builtins__", __builtins__)
        # Sandbox needs scalar literals too (SCENE_W=8.0, table_x=2.5, ...)
        # so helper-call args resolve. ``out`` keeps only iterables because
        # downstream ``_unroll_loop`` only iterates over collections.
        sandbox.update(all_literals)
        try:
            sandbox.update(self._collect_helper_funcs())
        except Exception:
            pass

        # Pass 2 a) Single-target Assign: rescue helper-call results (both
        # scalar and iterable) so a follow-up Assign that depends on them
        # (e.g. ``chair_positions = {k: norm_to_world(0.5, 0.4, SCENE_W,
        # SCENE_D)}``) can resolve. Only iterable results land in ``out``;
        # scalar results stay in the sandbox for downstream eval and for
        # ``_unroll_loop`` (see ``self._eval_sandbox`` cache below).
        # Pass 2 b) Tuple-target Assign: ``table_x, table_y = norm_to_world(...)``
        # is the canonical pattern that fed scalar table coordinates into
        # ``for ... in chair_positions.items(): ... face_target_rotation(pos,
        # (table_x, table_y))``. Without unpacking these, the chair loop
        # NameErrors on table_x even after ``chair_positions`` is rescued.
        for stmt_node in ast.walk(tree):
            if not isinstance(stmt_node, ast.Assign):
                continue
            if len(stmt_node.targets) != 1:
                continue
            target = stmt_node.targets[0]
            rhs = stmt_node.value
            if not any(isinstance(n, ast.Call) for n in ast.walk(rhs)):
                continue
            try:
                val = eval(ast.unparse(rhs), sandbox)
            except Exception:
                continue
            if isinstance(target, ast.Name):
                sandbox[target.id] = val
                if target.id not in out and isinstance(val, (list, dict, tuple, set)):
                    out[target.id] = val
            elif isinstance(target, (ast.Tuple, ast.List)):
                if not isinstance(val, (tuple, list)):
                    continue
                if len(target.elts) != len(val):
                    continue
                for elt, v in zip(target.elts, val):
                    if isinstance(elt, ast.Name):
                        sandbox[elt.id] = v

        self._eval_sandbox = sandbox
        # Sync scalar / iterable values into the helper sandbox so any
        # helper whose body references outer-scope vars (e.g. ``SCENE_W``,
        # ``table_x``) resolves them via ``__globals__`` at call time.
        # ``setdefault`` preserves already-installed helpers and stubs.
        helper_sb = getattr(self, "_helper_funcs_sandbox", None)
        if helper_sb is not None:
            for k, v in sandbox.items():
                if k in ("__builtins__",):
                    continue
                helper_sb.setdefault(k, v)
        return out

    def _helper_func_creator_names(self) -> List[str]:
        """Return names of top-level helper ``def``s whose body contains a
        primitive creator call (``create_box`` / ``create_cylinder`` /
        ``create_detailed_object``).

        These are the helpers that *indirectly* create objects when called
        — e.g. ``add_chair``, ``make_dining_chair``, ``spawn_armchair``.
        Used by ``_parse_all_objects`` so a loop like ``for ... in
        chair_positions.items(): add_chair(...)`` is recognised as an
        object-creating loop and dispatched to ``_unroll_loop``.

        Cached on the instance — the AST walk is non-trivial.
        """
        cached = getattr(self, "_helper_creator_cache", None)
        if cached is not None:
            return cached
        names: List[str] = []
        try:
            tree = ast.parse(self.code)
        except SyntaxError:
            self._helper_creator_cache = names
            return names
        primitives = {"create_box", "create_cylinder", "create_detailed_object"}
        for node in tree.body:
            if not isinstance(node, ast.FunctionDef):
                continue
            for sub in ast.walk(node):
                if (
                    isinstance(sub, ast.Call)
                    and isinstance(sub.func, ast.Name)
                    and sub.func.id in primitives
                ):
                    names.append(node.name)
                    break
        # Don't list the primitives themselves — they're handled by the
        # fast-path direct check.
        names = [n for n in names if n not in primitives]
        self._helper_creator_cache = names
        return names

    def _collect_helper_funcs(self) -> Dict[str, Any]:
        """Inject scene-level ``def`` helpers (e.g. ``yaw_to_face`` /
        ``to_world`` / ``add_chair``) into ``loop_env`` so loop bodies can
        call them without NameError when we ``exec`` them in the unroll
        sandbox.

        Each helper is exec'd in its own try/except — one bad helper (e.g.
        one that touches ``bpy`` at definition time) does not poison the rest.

        Critically, helper bodies that call ``create_box`` /
        ``create_cylinder`` (e.g. ``add_chair`` → 3× ``create_box``) bind
        those names through their own ``__globals__`` at *call* time, NOT
        at def time. So:

        1. We pre-stub ``create_box`` / ``create_cylinder`` /
           ``create_detailed_object`` in the shared ``sandbox_globals``
           dict BEFORE exec'ing helper defs, then exec all helpers into
           that same dict so each helper's ``__globals__`` references it.
        2. We cache the dict on ``self._helper_funcs_sandbox`` so
           ``_unroll_loop`` can later overwrite the stubs with its
           collector functions; helper invocations during loop simulation
           will then see the collectors via ``LOAD_GLOBAL`` at call time.

        The result is cached on ``self._helper_funcs_cache`` — re-running
        the AST walk + exec for every loop is unnecessarily slow.
        """
        cached = getattr(self, "_helper_funcs_cache", None)
        if cached is not None:
            return cached

        import math as _math
        helpers: Dict[str, Any] = {}
        try:
            tree = ast.parse(self.code)
        except SyntaxError:
            self._helper_funcs_cache = helpers
            return helpers

        src_lines = self.code.split('\n')
        sandbox_globals: Dict[str, Any] = dict(self.eval_env)
        sandbox_globals.setdefault("math", _math)
        sandbox_globals.setdefault("__builtins__", __builtins__)
        # Pre-stub primitive creators so any helper def that closes over
        # ``create_box`` / ``create_cylinder`` resolves to *this* dict
        # entry; ``_unroll_loop`` can then overwrite the stubs with
        # collector functions and helper invocations will see them.
        sandbox_globals.setdefault("create_box", lambda *a, **kw: None)
        sandbox_globals.setdefault("create_cylinder", lambda *a, **kw: None)
        sandbox_globals.setdefault("create_detailed_object", lambda *a, **kw: None)

        for node in tree.body:
            if not isinstance(node, ast.FunctionDef):
                continue
            end = getattr(node, "end_lineno", None)
            if end is None:
                continue
            chunk = "\n".join(src_lines[node.lineno - 1 : end])
            try:
                exec(chunk, sandbox_globals)
                fn = sandbox_globals.get(node.name)
                if callable(fn):
                    helpers[node.name] = fn
            except Exception:
                continue

        # Don't return the primitives themselves — they're stubs, not real
        # creators, and ``_unroll_loop`` installs its own collector for
        # the local LOAD_NAME path. Helper bodies still see them via
        # ``__globals__`` (which is sandbox_globals).
        for primitive in ("create_box", "create_cylinder", "create_detailed_object"):
            helpers.pop(primitive, None)

        self._helper_funcs_sandbox = sandbox_globals
        self._helper_funcs_cache = helpers
        return helpers

    def _unroll_loop(self, header: str, body_lines: List[str]):
        """Unroll a for-loop to extract all objects it creates."""
        import math
        
        # Parse loop: for i, xxx in enumerate(data): or for name, x, y, h in data: etc.
        # Strategy: build a safe eval environment, then simulate the loop
        
        body_text = '\n'.join(l.strip() for l in body_lines if l.strip())
        
        # Extract the iterable and loop variable(s)
        # Common patterns:
        #   for i, off in enumerate(chair_offsets):
        #   for i, (xn, yn, rot) in enumerate(armchair_data):
        #   for i, yn in enumerate(reception_chairs):
        #   for name, xn, yn, h in plants:
        #   for name, (x, y) in chair_positions.items():     ← dict literal
        
        # AST-based collector (replaces an old list-only regex). This now
        # captures dict / tuple / set literals AND helper-call results
        # (e.g. ``chair_positions = {k: norm_to_world(...)}``), and as a
        # side-effect populates ``self._eval_sandbox`` with every Assign we
        # could resolve — scalars (``SCENE_W=8.0``, ``table_x=...``),
        # iterables, and helper functions all live there.
        list_vars = self._collect_literal_iterables()
        
        # Try to simulate the loop
        try:
            # Use the full eval sandbox if available — it already contains
            # ``list_vars`` + helpers + scalar literals + scalar helper-call
            # results. This lets a chair-loop body that calls
            # ``face_target_rotation(pos, (table_x, table_y))`` resolve
            # ``table_x`` (which came from a tuple unpack of norm_to_world).
            loop_env = dict(self.eval_env)
            full_sandbox = getattr(self, "_eval_sandbox", None)
            if full_sandbox is not None:
                loop_env.update(full_sandbox)
            else:
                loop_env.update(list_vars)
                loop_env.update(self._collect_helper_funcs())
            loop_env['enumerate'] = enumerate
            loop_env['range'] = range
            
            # Execute the loop header + body, but replace create_box/create_cylinder
            # with a collector function
            collected = []
            
            def fake_create_box(name, loc, dims, rotation=(0, 0, 0), material=None, collection=None, show_direction=True):
                mat_name = ""
                for k, v in self.materials.items():
                    # material parameter in loop is a variable reference
                    pass
                collected.append(('box', name, loc, dims, rotation, material, collection))
            
            def fake_create_cylinder(name, loc, dims, rotation=(0, 0, 0), material=None, collection=None):
                collected.append(('cylinder', name, loc, dims, rotation, material, collection))
            
            loop_env['create_box'] = fake_create_box
            loop_env['create_cylinder'] = fake_create_cylinder
            # Critical for indirect creators: helpers like ``add_chair``
            # that internally call ``create_box`` resolve those names via
            # their own ``__globals__`` at call time, NOT via our
            # ``loop_env`` locals. We override the primitive stubs in the
            # shared helper sandbox so a ``add_chair(...)`` invocation
            # collects rather than NameErrors on ``bpy``.
            helper_sb = getattr(self, "_helper_funcs_sandbox", None)
            if helper_sb is not None:
                helper_sb['create_box'] = fake_create_box
                helper_sb['create_cylinder'] = fake_create_cylinder
                helper_sb['create_detailed_object'] = fake_create_box
            
            # Also put materials as their variable names pointing to their string names
            # so we can resolve them later
            mat_var_to_name = {}
            for var, info in self.materials.items():
                loop_env[var] = var  # pass the variable name as the value
                mat_var_to_name[var] = info['name']
            
            # Put collections as their variable names
            col_var_to_name = {}
            for var, cname in self.collections.items():
                loop_env[var] = var
                col_var_to_name[var] = cname
            
            # Build executable code
            loop_code = header + '\n'
            for bl in body_lines:
                # Only include lines that are part of the loop body
                if bl.strip():
                    loop_code += bl + '\n'
            
            # NOTE: scene helpers (yaw_to_face / to_world / …) are now in
            # ``loop_env`` so they're resolvable as locals during exec.
            exec(loop_code, {"__builtins__": {
                "range": range, "enumerate": enumerate, "len": len,
                "abs": abs, "min": min, "max": max, "round": round,
                "int": int, "float": float, "str": str,
                "tuple": tuple, "list": list, "dict": dict, "set": set,
                "sorted": sorted, "reversed": reversed,
            }}, loop_env)
            
            # Convert collected objects
            for shape, name, loc, dims, mat_ref, col_ref, *_ in collected:
                # Handle extra args if collected order varies
                if len(collected[0]) == 7:
                    shape, name, loc, dims, rot, mat_ref, col_ref = collected[0]
                
                # Resolve names
                try:
                    loc_tuple = tuple(float(v) for v in loc)
                except:
                    loc_tuple = (0.0, 0.0, 0.0)
                try:
                    dim_tuple = tuple(float(v) for v in dims)
                except:
                    dim_tuple = (1.0, 1.0, 1.0)
                
                break  # Just use collected directly below
            
            # Process all collected objects
            for item in collected:
                shape, name, loc, dims, rot, mat_ref, col_ref = item
                
                try:
                    loc_tuple = tuple(float(v) for v in loc)
                except:
                    loc_tuple = (0.0, 0.0, 0.0)
                try:
                    dim_tuple = tuple(float(v) for v in dims)
                except:
                    dim_tuple = (1.0, 1.0, 1.0)
                try:
                    rot_tuple = tuple(float(v) for v in rot) if rot else (0.0, 0.0, 0.0)
                except:
                    rot_tuple = (0.0, 0.0, 0.0)
                
                material_name = mat_var_to_name.get(mat_ref, "") if isinstance(mat_ref, str) else ""
                collection_name = col_var_to_name.get(col_ref, "Scene") if isinstance(col_ref, str) else "Scene"
                
                rotation_degrees = tuple(round(r * 180 / math.pi, 1) for r in rot_tuple)
                
                obj = ObjectInfo(
                    name=str(name),
                    shape=shape,
                    location=loc_tuple,
                    dimensions=dim_tuple,
                    rotation=rot_tuple,
                    rotation_degrees=rotation_degrees,
                    material_name=material_name,
                    collection=collection_name
                )
                
                if not self._is_architectural(obj.name):
                    self.objects.append(obj)
        
        except Exception as e:
            # Loud warning so this doesn't silently swallow whole groups of
            # objects (the dining-chair-loop bug stayed hidden for a while
            # exactly because this path was silent).
            print(
                f"⚠️  stage5_describe._unroll_loop failed for "
                f"header={header!r}: {type(e).__name__}: {e}",
                file=sys.stderr,
            )
            # Fallback: try to at least extract static-name objects from body.
            # We collect across multi-line calls so a multi-line create_box(...)
            # inside the loop body doesn't get cut off mid-call.
            j = 0
            while j < len(body_lines):
                bl_stripped = body_lines[j].strip()
                if 'create_box(' in bl_stripped or 'create_cylinder(' in bl_stripped:
                    full_call, end_idx = self._collect_full_call(body_lines, j)
                    obj = self._parse_single_call(full_call)
                    if obj and not self._is_architectural(obj.name):
                        self.objects.append(obj)
                    j = end_idx + 1
                    continue
                j += 1
    
    # ---------- Value Extraction Helpers ----------
    
    def _extract_string_value(self, s: str) -> Optional[str]:
        """Extract string value from an argument like '"Name"' or 'f"Name"'.

        Returns ``None`` for f-strings that contain ``{…}`` placeholders —
        those are runtime-templated names and must not be stored verbatim
        (otherwise a literal ``{idx}`` shows up in object names downstream).
        """
        s = s.strip()
        # Direct string: "Name" or 'Name'
        m = re.match(r'^["\']([^"\']+)["\']$', s)
        if m:
            return m.group(1)
        # Plain f-string with no placeholder: f"Name" / f'Name'
        m = re.match(r'^[fF]["\']([^"\'{}\\]+)["\']$', s)
        if m:
            return m.group(1)
        return None
    
    def _safe_eval_tuple(self, s: str) -> Tuple[float, float, float]:
        """Safely evaluate a tuple expression, handling nested function calls."""
        import math
        s = s.strip()

        # Try evaluating the whole expression first (handles variable refs like tv_console_dim)
        try:
            val = eval(s, {"__builtins__": {}}, self.eval_env)
            if isinstance(val, (tuple, list)) and len(val) >= 2:
                return tuple(float(v) for v in val[:3]) + ((0.0,) * max(0, 3 - len(val)))
        except:
            pass

        # Remove outer parens if present
        if s.startswith('(') and s.endswith(')'):
            inner = s[1:-1]
        else:
            inner = s

        # Split at top-level commas
        parts = self._split_top_level_args(inner)

        values = []
        for part in parts:
            part = part.strip()
            try:
                values.append(float(part))
            except ValueError:
                try:
                    val = eval(part, {"__builtins__": {}}, self.eval_env)
                    values.append(float(val))
                except:
                    values.append(0.0)
        
        while len(values) < 3:
            values.append(0.0)
        return tuple(values[:3])
    
    def _is_architectural(self, name: str) -> bool:
        """Check if this is an architectural element (wall, floor, etc.).

        IMPORTANT: We must NOT drop wall-mounted decorations / furniture whose
        names happen to contain an architectural word. For example:
          - "Wall_Art_1", "South_Wall_Art", "Wall_Clock", "Wall_Mirror"
          - "Floor_Lamp", "Floor_Vase"
          - "Window_Bench", "Door_Mat"
        These are *objects placed on* an architectural surface, not the
        surface itself. Previously this method used naive substring matching,
        which:
          1) matched "art" inside "partition_1", wrongly dropping walls, and
          2) matched "wall" inside "Wall_Art_1", wrongly dropping wall art.
        We now use word-boundary (token) matching and let decor/furniture
        tokens override architectural tokens.
        """
        import re
        name_lower = name.lower()

        def has_token(token: str) -> bool:
            # Match `token` as a whole word, where the separator can be any
            # non-letter character (underscore, dash, space, digit) or the
            # start/end of the string. This avoids "art" matching "partition"
            # or "wall" matching "drywall_trim".
            return bool(re.search(rf'(?:^|[^a-z]){re.escape(token)}(?:$|[^a-z])', name_lower))

        # Tokens that identify a piece of furniture or wall/ceiling decor.
        # If ANY of these appear as a whole token, the object is a decoration
        # or furniture piece placed on an architectural surface — NOT the
        # surface itself.
        decor_or_furniture_tokens = (
            # Wall art / pictures / mirrors / clocks
            'art', 'artwork', 'decor', 'decoration', 'poster', 'picture',
            'painting', 'mirror', 'clock', 'photo', 'photograph', 'print',
            'canvas', 'tapestry', 'mural',
            # Pin / memo / chalk / white / peg / bulletin boards
            'corkboard', 'pinboard', 'bulletin', 'chalkboard', 'whiteboard',
            'pegboard', 'noticeboard', 'memoboard', 'memo',
            # Soft decor
            'wreath', 'garland', 'macrame', 'dreamcatcher', 'pennant',
            'banner', 'flag', 'plaque', 'monogram',
            # Shelves / hooks / racks mounted on wall
            'shelf', 'shelves', 'bookshelf', 'bookshelves',
            'hook', 'rack', 'bracket', 'sconce', 'hanger',
            # Lighting / plants / vases on surfaces
            'lamp', 'light', 'lantern', 'chandelier',
            'vase', 'plant', 'planter', 'pot',
            # Seating / tables / storage (floor-placed furniture)
            'bench', 'stool', 'chair', 'sofa', 'couch', 'armchair', 'ottoman',
            'table', 'desk', 'nightstand', 'dresser', 'cabinet', 'wardrobe',
            'bookcase', 'sideboard', 'console', 'shelving',
            'bed', 'headboard', 'footboard', 'mattress',
            # Floor coverings and misc
            'mat', 'rug', 'carpet', 'runner',
            # Doormat, doorstop, etc. (still decor / utility)
            'doormat', 'doorstop',
            # Kids / storage / toys
            'toy', 'bin', 'basket', 'crate', 'box', 'hamper',
        )
        if any(has_token(t) for t in decor_or_furniture_tokens):
            return False

        # Tokens that mark a genuine architectural structure.
        architectural_tokens = (
            'floor', 'wall', 'ceiling', 'partition', 'door', 'window',
            'curtain', 'blinds', 'shutter', 'entrance', 'baseboard',
            'skirting', 'molding', 'moulding', 'cornice', 'beam',
            'column', 'pillar', 'arch', 'archway', 'threshold',
        )
        return any(has_token(t) for t in architectural_tokens)


# ==============================================================================
# Stage Describe Runner
# ==============================================================================
class StageDescribeRunner:
    """Stage Describe Runner - Generate object descriptions and room style"""
    
    def __init__(
        self,
        image_path: str = None,
        scene_code_path: str = None,
        output_dir: str = None,
        use_memory: bool = True,
        verbose: bool = True,
        memory_file: str = "agent_memory.jsonl",
        model: str = None,
        base_url: str = None,
        api_key: str = None,
    ):
        self.image_path = image_path
        self.scene_code_path = scene_code_path
        self.output_dir = output_dir or os.path.join(current_dir, "pipeline_output", "stage5_describe")
        self.use_memory = use_memory
        self.verbose = verbose
        
        # Initialize
        self.memory = Memory(workspace_dir=current_dir, memory_file=memory_file) if use_memory else None
        self.llm = LLMClient(model=model, base_url=base_url, api_key=api_key)
        self.scene_type_info = self._load_scene_type_info()
        
        # Data
        self.scene_code: str = None
        self.objects: List[ObjectInfo] = []
        self.room_style: RoomStyleInfo = None
        self.inventory_objects: List[Dict[str, Any]] = []
        self.orphan_objects: List[Dict[str, Any]] = []
    
    def _load_scene_type_info(self) -> Dict[str, Any]:
        fallback = {
            "scene_type": "other",
            "confidence": 0.0,
            "reasoning": "no scene_type in memory",
            "lab_subtype": None,
            "industrial_subtype": None,
            "source": "fallback",
        }
        if not self.memory:
            return fallback
        try:
            from scene_classifier import read_scene_type  # type: ignore
            return read_scene_type(self.memory)
        except Exception as exc:
            if self.verbose:
                print(f"Stage5: cannot read scene_type ({exc}); using generic prompts")
            return fallback

    def _is_industrial_scene(self) -> bool:
        return (
            (self.scene_type_info or {}).get("scene_type") == "industrial"
            and float((self.scene_type_info or {}).get("confidence", 0.0) or 0.0) >= 0.5
        )

    def _log(self, msg: str, level: str = "info"):
        if self.verbose:
            prefix = {
                "info": "ℹ️", 
                "success": "✅", 
                "warning": "⚠️", 
                "error": "❌", 
                "step": "📋",
                "object": "🪑",
                "style": "🎨"
            }.get(level, "")
            print(f"{prefix} {msg}")
    
    def _encode_image(self, path: str) -> tuple:
        """Encode image to base64"""
        with open(path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("utf-8")
        ext = os.path.splitext(path)[1].lower()
        mime = {".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png"}.get(ext, "image/png")
        return b64, mime
    
    def _load_data(self) -> bool:
        """Load required data"""
        self._log("Loading data...", "step")
        
        # 1. Load scene code
        if self.scene_code_path and os.path.exists(self.scene_code_path):
            with open(self.scene_code_path, "r", encoding="utf-8") as f:
                self.scene_code = f.read()
            self._log(f"Scene code: {self.scene_code_path}", "success")
        elif self.use_memory:
            # Try to get Stage4 or Stage3 code from Memory
            for stage in ["stage4", "stage3"]:
                entry = self.memory.get_latest(stage=stage, type="result")
                if entry:
                    self.scene_code = entry.content
                    self._log(f"Scene code: from Memory ({stage})", "success")
                    break
        
        if not self.scene_code:
            run_dir = os.path.dirname(self.output_dir)
            for candidate in (
                os.path.join(run_dir, "stage4", "stage4_output.py"),
                os.path.join(run_dir, "stage4", "stage4_clean.py"),
                os.path.join(run_dir, "stage3", "stage3_output.py"),
            ):
                if os.path.exists(candidate):
                    with open(candidate, "r", encoding="utf-8") as f:
                        self.scene_code = f.read()
                    self._log(f"Scene code: from sibling dir - {candidate}", "success")
                    break

        if not self.scene_code:
            self._log("Scene code not found!", "error")
            self._log("   Please run Stage 3/4 first, or use --scene-code", "error")
            return False
        
        # 2. Load reference image
        if not self.image_path and self.use_memory:
            stage1_entry = self.memory.get_latest(stage="stage1", type="result")
            if stage1_entry:
                self.image_path = stage1_entry.metadata.get("image_path")
        
        if self.image_path and os.path.exists(self.image_path):
            self._log(f"Reference image: {self.image_path}", "success")
        else:
            self._log("Reference image not found!", "error")
            self._log("   Please use --image to specify the image path", "error")
            return False
        
        self._load_inventory_objects()
        return True

    @staticmethod
    def _coerce_json_data(data: Any) -> Any:
        if isinstance(data, str):
            try:
                return json.loads(data)
            except Exception:
                return None
        return data

    @staticmethod
    def _normalize_match_text(text: str) -> str:
        text = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", text or "")
        text = text.lower()
        text = re.sub(r"\bobj[_\s-]*\d+\b", " ", text)
        text = re.sub(r"[^a-z0-9]+", " ", text)
        stop = {
            "the", "a", "an", "and", "of", "on", "in", "near", "with",
            "section", "area", "zone", "object", "item", "small",
            "lab", "laboratory", "bench", "worktop", "top",
        }
        tokens = [t for t in text.split() if t and t not in stop]
        return " ".join(tokens)

    @classmethod
    def _match_tokens(cls, text: str) -> set:
        return set(cls._normalize_match_text(text).split())

    @staticmethod
    def _safe_read_json(path: str) -> Optional[Dict[str, Any]]:
        if not path or not os.path.exists(path):
            return None
        try:
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return None

    def _load_inventory_objects(self):
        """Load Stage 1/2 semantic inventory for orphan reporting.

        Stage 7 descriptions remain bbox-driven, but this side inventory lets
        downstream stages see semantic objects that Stage 3/4 did not create.
        """
        stage1_data = None
        stage2_minors: List[Dict[str, Any]] = []

        if self.use_memory:
            stage1_entry = self.memory.get_latest(stage="stage1", type="result")
            if stage1_entry:
                stage1_data = self._coerce_json_data(stage1_entry.content)

            minor_entry = self.memory.get_latest(stage="stage2", type="minor_objects")
            if minor_entry:
                minor_data = self._coerce_json_data(minor_entry.content) or {}
                stage2_minors = minor_data.get("minor_objects", []) or []

            if not stage2_minors:
                stage2_entry = self.memory.get_latest(stage="stage2", type="result")
                if stage2_entry:
                    stage2_data = self._coerce_json_data(stage2_entry.content) or {}
                    stage2_minors = stage2_data.get("minor_objects", []) or []

        run_dir = os.path.dirname(self.output_dir)
        if not stage1_data:
            stage1_data = self._safe_read_json(
                os.path.join(run_dir, "stage1", "stage1_output.json")
            )

        if not stage2_minors:
            sidecar = self._safe_read_json(
                os.path.join(run_dir, "stage2", "stage2_minor_objects.json")
            )
            if sidecar:
                stage2_minors = sidecar.get("minor_objects", []) or []

        inventory: List[Dict[str, Any]] = []
        id_to_name: Dict[str, str] = {}

        if isinstance(stage1_data, dict):
            for zone in stage1_data.get("decoupled_zones", []) or []:
                zone_id = zone.get("zone_id")
                zone_name = zone.get("zone_name")
                for obj in zone.get("object_hierarchy", []) or []:
                    object_id = obj.get("object_id") or obj.get("id")
                    name = obj.get("name") or obj.get("label") or object_id or "unknown"
                    id_to_name[object_id] = name
                    inventory.append({
                        "source_stage": "stage1",
                        "source_object_id": object_id,
                        "name": name,
                        "category": obj.get("category"),
                        "placement_type": obj.get("placement_type"),
                        "parent_object": obj.get("parent_object"),
                        "parent_name": None,
                        "zone_id": zone_id,
                        "zone_name": zone_name,
                        "structure_hint": obj.get("structure_hint"),
                        "industrial_role": obj.get("industrial_role"),
                    })

        for item in inventory:
            parent_id = item.get("parent_object")
            if parent_id in id_to_name:
                item["parent_name"] = id_to_name[parent_id]

        by_id = {
            item.get("source_object_id"): item
            for item in inventory
            if item.get("source_object_id")
        }

        for minor in stage2_minors:
            object_id = minor.get("id") or minor.get("object_id")
            existing = by_id.get(object_id)
            target = existing
            if not target:
                target = {
                    "source_stage": "stage2",
                    "source_object_id": object_id,
                    "name": minor.get("label") or minor.get("name") or object_id or "unknown",
                    "category": minor.get("category", "minor"),
                    "placement_type": minor.get("placement_type"),
                    "parent_object": minor.get("parent_id"),
                    "parent_name": minor.get("parent_label"),
                    "zone_id": minor.get("zone_id"),
                    "zone_name": None,
                    "structure_hint": None,
                    "industrial_role": None,
                }
                inventory.append(target)
            target["stage2_minor"] = {
                "label": minor.get("label") or minor.get("name"),
                "parent_id": minor.get("parent_id"),
                "parent_label": minor.get("parent_label"),
                "parent_kind": minor.get("parent_kind"),
            }
            if minor.get("parent_label"):
                target["parent_name"] = minor.get("parent_label")

        self.inventory_objects = inventory
        if inventory:
            self._log(
                f"Loaded inventory: {len(inventory)} Stage1/2 objects "
                f"({len(stage2_minors)} Stage2 minors)",
                "success",
            )

    def _find_code_match(self, candidate_name: str, allow_loose: bool = True) -> Optional[str]:
        if not candidate_name:
            return None
        cand_norm = self._normalize_match_text(candidate_name)
        cand_tokens = set(cand_norm.split())
        if not cand_tokens:
            return None

        best_name = None
        best_score = 0.0
        for obj in self.objects:
            code_norm = self._normalize_match_text(obj.name)
            code_tokens = set(code_norm.split())
            if not code_tokens:
                continue
            if cand_norm == code_norm:
                return obj.name
            overlap = len(cand_tokens & code_tokens)
            score = overlap / max(len(cand_tokens), len(code_tokens))
            if cand_tokens.issubset(code_tokens) or code_tokens.issubset(cand_tokens):
                score = max(score, 0.75)
            if score > best_score:
                best_score = score
                best_name = obj.name

        threshold = 0.45 if allow_loose else 0.7
        return best_name if best_score >= threshold else None

    def _build_orphan_inventory(self):
        """Mark Stage1/2 inventory objects that have no Stage3/4 code object."""
        if not self.inventory_objects:
            self.orphan_objects = []
            return

        id_to_item = {
            item.get("source_object_id"): item
            for item in self.inventory_objects
            if item.get("source_object_id")
        }
        orphans = []

        for item in self.inventory_objects:
            name = item.get("name") or ""
            placement = item.get("placement_type")
            category = item.get("category")
            allow_loose = category == "major" or placement in {"floor", "wall"}
            code_match = self._find_code_match(name, allow_loose=allow_loose)

            parent_name = item.get("parent_name")
            parent_code_match = self._find_code_match(parent_name, allow_loose=True)
            if not parent_code_match:
                parent_id = item.get("parent_object")
                parent_item = id_to_item.get(parent_id)
                if parent_item:
                    parent_code_match = parent_item.get("code_match_name")

            item["represented_in_code"] = bool(code_match)
            item["code_match_name"] = code_match
            item["parent_code_match_name"] = parent_code_match

            if code_match:
                continue

            if placement == "surface":
                reason = "listed as a surface object in Stage 1/2 but absent from Stage 3/4 bbox code"
            elif placement == "wall":
                reason = "listed as a wall object in Stage 1 but absent from Stage 3/4 bbox code"
            elif placement == "floor":
                reason = "listed as a floor object in Stage 1/2 but absent from Stage 3/4 bbox code"
            else:
                reason = "listed in Stage 1/2 but absent from Stage 3/4 bbox code"

            orphan = dict(item)
            orphan["orphan_reason"] = reason
            orphan.setdefault("object_type", "")
            orphan.setdefault("appearance", "")
            orphan.setdefault("material_description", "")
            orphan.setdefault("color_description", "")
            orphan.setdefault("description", "")
            orphans.append(orphan)

        self.orphan_objects = orphans
        self._log(
            f"Inventory reconciliation: {len(orphans)} orphan objects",
            "warning" if orphans else "success",
        )

    def _fallback_describe_orphan(self, orphan: Dict[str, Any]) -> Dict[str, Any]:
        name = orphan.get("name") or "Object"
        parent = orphan.get("parent_name")
        placement = orphan.get("placement_type") or "unknown"
        base = f"{name} listed by Stage 1/2 as a {placement} object"
        if parent:
            base += f" associated with {parent}"
        base += ", but not instantiated in the Stage 3/4 Blender code."
        orphan["object_type"] = orphan.get("object_type") or name.lower()
        orphan["appearance"] = orphan.get("appearance") or "Visible in the source image inventory, exact geometry not present in code."
        orphan["material_description"] = orphan.get("material_description") or "unspecified material"
        orphan["color_description"] = orphan.get("color_description") or "image-dependent color"
        orphan["description"] = orphan.get("description") or base
        return orphan

    def _generate_orphan_descriptions(self) -> bool:
        if not self.orphan_objects:
            return True

        self._log("Generating orphan object descriptions...", "step")
        orphan_rows = []
        for i, orphan in enumerate(self.orphan_objects):
            orphan_rows.append(
                f"{i + 1}. id={orphan.get('source_object_id')} | "
                f"name={orphan.get('name')} | category={orphan.get('category')} | "
                f"placement={orphan.get('placement_type')} | "
                f"parent={orphan.get('parent_name')} | zone={orphan.get('zone_name') or orphan.get('zone_id')} | "
                f"industrial_role={orphan.get('industrial_role')} | structure_hint={orphan.get('structure_hint')}\n"
            )

        system_prompt = """You describe semantic inventory objects that were detected in Stage 1/2 but are missing from the generated Blender bbox code.

Output ONLY valid JSON with this exact structure:
{
  "orphan_objects": [
    {
      "source_object_id": "same id from input",
      "name": "same name from input",
      "object_type": "specific type",
      "appearance": "brief visual appearance based on the image and inventory context",
      "material_description": "likely material grounded in the image",
      "color_description": "likely visible color",
      "description": "one sentence explaining what it is and where it belongs"
    }
  ]
}

Rules:
- Use English.
- Do not invent unsupported objects; describe only the input orphan list.
- Preserve source_object_id and name exactly.
- For lab surface objects, mention the parent bench/surface when given.
- For industrial scenes, preserve machine/storage/safety semantics: CNC, robot cell, conveyor, pallet rack, control cabinet, safety fence, workbench, inspection station, tooling, bins, and material-flow equipment should not be described as residential furniture or decor."""

        user_content = f"""Reference image plus orphan inventory:

{"".join(orphan_rows)}

Generate compact descriptions for every orphan object."""

        try:
            b64, mime = self._encode_image(self.image_path)
            response = self.llm.invoke([
                SystemMessage(content=system_prompt),
                HumanMessage(content=[
                    {"type": "image_url", "image_url": {"url": f"data:{mime};base64,{b64}"}},
                    {"type": "text", "text": user_content},
                ]),
            ])
            result = self._extract_json(response)
            desc_rows = (result or {}).get("orphan_objects", [])
            desc_by_id = {
                row.get("source_object_id"): row
                for row in desc_rows
                if row.get("source_object_id")
            }

            enriched = []
            for orphan in self.orphan_objects:
                desc = desc_by_id.get(orphan.get("source_object_id"))
                if desc:
                    for key in (
                        "object_type", "appearance", "material_description",
                        "color_description", "description",
                    ):
                        orphan[key] = desc.get(key, orphan.get(key, ""))
                enriched.append(self._fallback_describe_orphan(orphan))
            self.orphan_objects = enriched
            self._log(f"Generated descriptions for {len(self.orphan_objects)} orphan objects", "success")
            return True
        except Exception as e:
            self._log(f"Error generating orphan descriptions: {e}", "warning")
            self.orphan_objects = [
                self._fallback_describe_orphan(orphan)
                for orphan in self.orphan_objects
            ]
            return False
    
    def _parse_code(self) -> bool:
        """Parse objects from code"""
        self._log("Parsing objects from code...", "step")
        
        parser = BlenderCodeParser(self.scene_code)
        self.objects = parser.parse()
        
        self._log(f"Found {len(self.objects)} objects", "success")
        
        # Print object list
        for obj in self.objects:
            self._log(f"  - {obj.name}: {obj.shape}, location={obj.location}, dimensions={obj.dimensions}", "object")
        
        self._build_orphan_inventory()
        return len(self.objects) > 0
    
    def _generate_object_descriptions(self) -> bool:
        """Use LLM to generate descriptions for each object"""
        self._log("Generating object descriptions...", "step")
        
        # Build object list string
        objects_list = []
        for i, obj in enumerate(self.objects):
            objects_list.append(f"""
{i+1}. **{obj.name}**
   - Shape: {obj.shape}
   - Location (x, y, z): {obj.location}
   - Dimensions (width, depth, height): {obj.dimensions}
   - Rotation (degrees): {obj.rotation_degrees}
   - Material name: {obj.material_name}
   - Collection/Zone: {obj.collection}
""")
        
        if self._is_industrial_scene():
            subtype = (self.scene_type_info or {}).get("industrial_subtype") or "general"
            system_prompt = f"""You are a manufacturing facility scene expert. Based on the provided top-down factory / industrial floor image and the object list extracted from code, generate detailed descriptions for each object. Scene subtype: {subtype}.

For each object, analyze the image and provide:
1. **object_type**: The specific industrial object type, such as "CNC machining center", "lathe", "conveyor segment", "robot arm cell", "safety fence", "pallet rack", "control cabinet", "tool cabinet", "workbench", "inspection table", "server rack", or "parts bin rack". Do NOT downgrade machines to generic cabinets/tables.
2. **appearance**: Describe the visible industrial structure: enclosure, belt, rollers, robot pedestal/arm, fence posts/rails, rack uprights/beams, control panel, doors, windows, warning beacons, vents, or access panels. For benches/worktables, mention visible tools, jigs, fixtures, trays, bins, workpieces, clipboards, or tablets on top when present.
3. **material_description**: Use industrial materials such as powder-coated metal, painted metal, stainless steel, brushed aluminum, rubber belt, glass/acrylic window, concrete, epoxy-coated floor, or plastic bins.
4. **color_description**: Describe dominant industrial colors, including safety yellow, emergency red, grey machine panels, black rubber, stainless silver, and floor-marking colors when visible.
5. **description**: A complete 1-2 sentence description combining object function, structure, material, and placement.

Output ONLY valid JSON (no markdown, no explanation), following this exact structure:
{{
  "objects": [
    {{
      "name": "object_name_from_code",
      "object_type": "specific object type",
      "appearance": "appearance description",
      "material_description": "material description",
      "color_description": "color description",
      "description": "complete description in 1-2 sentences"
    }}
  ]
}}

Important:
- Match each object by its name from the code.
- Base descriptions on what you SEE in the image and on the object's name/geometry.
- Preserve factory semantics: conveyors are conveyors, robot cells are robot cells, racks are open racks, safety fences are guarded barriers.
- Do not invent residential decor such as plants, pillows, candles, rugs, framed art, or vases.
- Keep loose tools, workpieces, bins, and paperwork as surface props in the description; downstream stages may place them separately."""
        else:
            system_prompt = """You are an interior design expert. Based on the provided top-down floor plan image and the object list extracted from code, generate detailed descriptions for each object.

For each object, analyze the image and provide:
1. **object_type**: What type of furniture/item is this (e.g., "king bed", "armchair", "nightstand", "table lamp")
2. **appearance**: Describe the appearance seen in the image (shape, style, design features). **If this object has a horizontal work surface visible from above (table, desk, island, lab bench, counter, shelf top), explicitly describe tabletop clutter you see** — distinct clusters, approximate counts ("several bottles", "two racks"), and rough layout (left/right/center). Pay equal attention to **perimeter benches and secondary surfaces** as to the room-center island; do not describe only the focal surface.
3. **material_description**: Describe the material (e.g., "wood", "fabric", "metal", "glass")
4. **color_description**: Describe the color (e.g., "warm white", "dark brown wood grain", "beige fabric")
5. **description**: A complete description combining all above in 1-2 sentences

Output ONLY valid JSON (no markdown, no explanation), following this exact structure:
{
  "objects": [
    {
      "name": "object_name_from_code",
      "object_type": "specific object type",
      "appearance": "appearance description",
      "material_description": "material description",
      "color_description": "color description",
      "description": "complete description in 1-2 sentences"
    }
  ]
}

Important:
- Match each object by its name from the code
- Base your descriptions on what you SEE in the image
- Use English for all descriptions
- Be specific about materials and colors based on the image
- **Small surface props**: For tables, lab benches, islands, counters, and desks, mention visible items on top (glassware, racks, electronics, dishes, decor) when present — downstream stages use your wording as weak supervision for surface-bound small-object placement"""

        user_content = f"""Please analyze this top-down floor plan and generate descriptions for the following objects:

## Object List (parsed from code)
{"".join(objects_list)}

Please generate detailed English descriptions for each object, output in JSON format.
"""
        
        b64, mime = self._encode_image(self.image_path)
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=[
                {"type": "image_url", "image_url": {"url": f"data:{mime};base64,{b64}"}},
                {"type": "text", "text": user_content}
            ])
        ]
        
        try:
            response = self.llm.invoke(messages)
            result = self._extract_json(response)
            
            if result and "objects" in result:
                # Update object descriptions
                desc_map = {obj["name"]: obj for obj in result["objects"]}
                
                for obj in self.objects:
                    if obj.name in desc_map:
                        desc = desc_map[obj.name]
                        obj.object_type = desc.get("object_type", "")
                        obj.appearance = desc.get("appearance", "")
                        obj.material_description = desc.get("material_description", "")
                        obj.color_description = desc.get("color_description", "")
                        obj.description = desc.get("description", "")
                
                self._log(f"Successfully generated {len(result['objects'])} object descriptions", "success")
                return True
            else:
                self._log("Failed to parse object descriptions", "warning")
                return False
                
        except Exception as e:
            self._log(f"Error generating descriptions: {e}", "error")
            import traceback
            traceback.print_exc()
            return False
    
    def _generate_room_style(self) -> bool:
        """Generate room overall style description"""
        self._log("Analyzing room style...", "style")
        
        if self._is_industrial_scene():
            subtype = (self.scene_type_info or {}).get("industrial_subtype") or "general"
            system_prompt = f"""You are an industrial facility visual analyst. Analyze the provided top-down factory / industrial floor image and determine the overall facility style and material palette. Scene subtype: {subtype}.

Output ONLY valid JSON (no markdown, no explanation), following this exact structure:
{{
  "room_style": {{
    "style_name": "style name (e.g., Clean Manufacturing Floor, Machine Shop, Robotic Assembly Cell, Warehouse Industrial)",
    "style_description": "detailed style description in 2-3 sentences",
    "color_palette": ["primary color 1", "primary color 2", "primary color 3"],
    "mood": "atmosphere description (e.g., utilitarian and organized, clean and technical, heavy-duty and active)",
    "era": "era style (e.g., contemporary industrial, modern automated, legacy workshop)",
    "keywords": ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5"]
  }}
}}

Analyze:
- Machine and equipment color scheme
- Safety colors and floor markings
- Material choices such as concrete, epoxy floor, painted metal, stainless steel, rubber belts, acrylic guards
- Facility layout: cells, aisles, racks, conveyor lines, workbenches
- Overall industrial atmosphere

Use English for all descriptions. Do not describe the space as cozy residential interior design."""
        else:
            system_prompt = """You are an interior design expert. Analyze the provided top-down floor plan image and determine the overall room style.

Output ONLY valid JSON (no markdown, no explanation), following this exact structure:
{
  "room_style": {
    "style_name": "style name (e.g., Modern Minimalist, Scandinavian, Industrial, Contemporary)",
    "style_description": "detailed style description in 2-3 sentences",
    "color_palette": ["primary color 1", "primary color 2", "primary color 3"],
    "mood": "atmosphere description (e.g., warm and cozy, clean and bright, elegant and refined)",
    "era": "era style (e.g., contemporary, vintage, eclectic)",
    "keywords": ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5"]
  }
}

Analyze:
- Color scheme (warm/cool, neutral/vibrant)
- Material choices (wood, fabric, metal, etc.)
- Furniture style and arrangement
- Overall atmosphere

Use English for all descriptions."""

        user_content = "Please analyze the overall style of this room from the top-down view, output the style description in JSON format."
        
        b64, mime = self._encode_image(self.image_path)
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=[
                {"type": "image_url", "image_url": {"url": f"data:{mime};base64,{b64}"}},
                {"type": "text", "text": user_content}
            ])
        ]
        
        try:
            response = self.llm.invoke(messages)
            result = self._extract_json(response)
            
            if result and "room_style" in result:
                style_data = result["room_style"]
                self.room_style = RoomStyleInfo(
                    style_name=style_data.get("style_name", "Unknown"),
                    style_description=style_data.get("style_description", ""),
                    color_palette=style_data.get("color_palette", []),
                    mood=style_data.get("mood", ""),
                    era=style_data.get("era", ""),
                    keywords=style_data.get("keywords", [])
                )
                
                self._log(f"Room style: {self.room_style.style_name}", "success")
                self._log(f"  Color palette: {', '.join(self.room_style.color_palette)}", "style")
                self._log(f"  Mood: {self.room_style.mood}", "style")
                return True
            else:
                self._log("Failed to parse room style", "warning")
                return False
                
        except Exception as e:
            self._log(f"Error analyzing style: {e}", "error")
            return False
    
    def _extract_json(self, text: str) -> dict:
        """Extract JSON from response"""
        # Try direct parsing
        try:
            return json.loads(text)
        except:
            pass
        
        # Try extracting from code blocks
        patterns = [
            r'```json\s*([\s\S]*?)\s*```',
            r'```\s*([\s\S]*?)\s*```',
            r'\{[\s\S]*\}'
        ]
        
        for pattern in patterns:
            match = re.search(pattern, text)
            if match:
                try:
                    json_str = match.group(1) if '```' in pattern else match.group(0)
                    return json.loads(json_str)
                except:
                    continue
        
        return None
    
    def _save_results(self):
        """Save results"""
        os.makedirs(self.output_dir, exist_ok=True)
        
        # 1. Save complete result JSON
        result = {
            "room_style": self.room_style.to_dict() if self.room_style else {},
            "objects": [obj.to_dict() for obj in self.objects],
            "inventory_objects": self.inventory_objects,
            "orphan_objects": self.orphan_objects,
            "orphan_summary": {
                "total_inventory_objects": len(self.inventory_objects),
                "represented_inventory_objects": sum(
                    1 for obj in self.inventory_objects
                    if obj.get("represented_in_code")
                ),
                "orphan_objects": len(self.orphan_objects),
            },
            "summary": {
                "total_objects": len(self.objects),
                "total_inventory_objects": len(self.inventory_objects),
                "orphan_objects": len(self.orphan_objects),
                "style_name": self.room_style.style_name if self.room_style else "Unknown",
                "image_path": self.image_path
            }
        }
        
        output_path = os.path.join(self.output_dir, "describe_output.json")
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(result, f, ensure_ascii=False, indent=2)
        self._log(f"Full result: {output_path}", "success")

        orphan_path = os.path.join(self.output_dir, "describe_orphans.json")
        with open(orphan_path, "w", encoding="utf-8") as f:
            json.dump({
                "orphan_summary": result["orphan_summary"],
                "orphan_objects": self.orphan_objects,
            }, f, ensure_ascii=False, indent=2)
        self._log(f"Orphan report: {orphan_path}", "success")
        
        # 2. Save Markdown report
        md_content = self._generate_markdown_report()
        md_path = os.path.join(self.output_dir, "describe_report.md")
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)
        self._log(f"Report: {md_path}", "success")
        
        # 3. Save to Memory
        if self.use_memory:
            self.memory.add(
                stage="stage5_describe",
                type="result",
                content=json.dumps(result, ensure_ascii=False, indent=2),
                metadata={
                    "title": "Stage Describe - Object Descriptions",
                    "summary": f"{len(self.objects)} objects, style: {self.room_style.style_name if self.room_style else 'unknown'}",
                    "output_file": output_path,
                    "orphan_report_file": orphan_path,
                    "report_file": md_path,
                    "image_path": self.image_path,
                    "total_objects": len(self.objects),
                    "total_inventory_objects": len(self.inventory_objects),
                    "orphan_objects_count": len(self.orphan_objects),
                    "style_name": self.room_style.style_name if self.room_style else "Unknown"
                },
                tags=["stage5_describe", "object_description", "room_style"]
            )
            self._log("Saved to Memory", "success")
    
    def _generate_markdown_report(self) -> str:
        """Generate Markdown format report"""
        lines = [
            "# Scene Object Description Report",
            "",
            f"**Generated Time**: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Reference Image**: {self.image_path}",
            "",
            "---",
            "",
            "## 1. Room Overall Style",
            ""
        ]
        
        if self.room_style:
            lines.extend([
                f"**Style Name**: {self.room_style.style_name}",
                "",
                f"**Style Description**: {self.room_style.style_description}",
                "",
                f"**Color Palette**: {', '.join(self.room_style.color_palette)}",
                "",
                f"**Mood**: {self.room_style.mood}",
                "",
                f"**Era Style**: {self.room_style.era}",
                "",
                f"**Keywords**: {', '.join(self.room_style.keywords)}",
            ])
        
        lines.extend([
            "",
            "---",
            "",
            "## 2. Object Details",
            ""
        ])
        
        # Group by collection
        collections = {}
        for obj in self.objects:
            col = obj.collection or "Other"
            if col not in collections:
                collections[col] = []
            collections[col].append(obj)
        
        for collection_name, objs in collections.items():
            lines.extend([
                f"### {collection_name}",
                ""
            ])
            
            for obj in objs:
                lines.extend([
                    f"#### {obj.name}",
                    "",
                    f"| Property | Value |",
                    f"|----------|-------|",
                    f"| Object Type | {obj.object_type} |",
                    f"| Shape | {obj.shape} |",
                    f"| Location (x, y, z) | {obj.location} |",
                    f"| Dimensions (w, d, h) | {obj.dimensions} |",
                    f"| Rotation (degrees) | {obj.rotation_degrees} |",
                    f"| Material | {obj.material_description} |",
                    f"| Color | {obj.color_description} |",
                    "",
                    f"**Description**: {obj.description}",
                    "",
                    f"**Appearance**: {obj.appearance}",
                    "",
                    "---",
                    ""
                ])
        
        if self.orphan_objects:
            lines.extend([
                "",
                "---",
                "",
                "## 3. Stage1/Stage2 Inventory Orphans",
                "",
                (
                    "These objects were listed in the semantic inventory but "
                    "were not instantiated in the Stage 3/4 Blender code."
                ),
                "",
            ])
            for orphan in self.orphan_objects:
                lines.extend([
                    f"### {orphan.get('name')}",
                    "",
                    f"- Source ID: {orphan.get('source_object_id')}",
                    f"- Category: {orphan.get('category')}",
                    f"- Placement: {orphan.get('placement_type')}",
                    f"- Parent: {orphan.get('parent_name') or orphan.get('parent_object')}",
                    f"- Parent Code Match: {orphan.get('parent_code_match_name')}",
                    f"- Reason: {orphan.get('orphan_reason')}",
                    "",
                    f"**Description**: {orphan.get('description', '')}",
                    "",
                ])

        return "\n".join(lines)
    
    def run(self) -> Tuple[bool, Dict]:
        """
        Run Stage Describe
        
        Returns:
            (success, result_dict)
        """
        print("\n" + "=" * 60)
        print("🎨 Stage Describe - Object Description & Room Style Analysis")
        print("=" * 60)
        
        # 1. Load data
        if not self._load_data():
            return False, {}
        
        # 2. Parse code
        print("\n--- Part A: Code Parsing ---")
        if not self._parse_code():
            self._log("No objects found in code", "warning")
        
        # 3. Generate object descriptions
        print("\n--- Part B: Object Description Generation ---")
        self._generate_object_descriptions()
        self._generate_orphan_descriptions()
        
        # 4. Analyze room style
        print("\n--- Part C: Room Style Analysis ---")
        self._generate_room_style()
        
        # 5. Save results
        print("\n--- Part D: Save Results ---")
        self._save_results()
        
        # Build return result
        result = {
            "room_style": self.room_style.to_dict() if self.room_style else {},
            "objects": [obj.to_dict() for obj in self.objects],
            "inventory_objects": self.inventory_objects,
            "orphan_objects": self.orphan_objects,
            "total_objects": len(self.objects),
            "orphan_objects_count": len(self.orphan_objects),
        }
        
        print("\n" + "=" * 60)
        print("✅ Stage Describe Complete!")
        print(f"   Total objects: {len(self.objects)}")
        print(f"   Orphan inventory objects: {len(self.orphan_objects)}")
        print(f"   Room style: {self.room_style.style_name if self.room_style else 'Unknown'}")
        print(f"   Output directory: {self.output_dir}")
        print("=" * 60)
        
        return True, result


# ==============================================================================
# Command Line Entry
# ==============================================================================
def show_memory_status():
    """Show Memory status"""
    memory = Memory(workspace_dir=current_dir)
    
    print("=" * 60)
    print("📋 Memory Status")
    print("=" * 60)
    
    for stage in ["stage1", "stage2", "stage3", "stage4", "stage5_describe"]:
        entry = memory.get_latest(stage=stage, type="result")
        if entry:
            title = entry.metadata.get("title", "untitled")
            from datetime import datetime
            time_str = datetime.fromtimestamp(entry.timestamp).strftime("%m-%d %H:%M")
            print(f"✅ {stage}: {title} ({time_str})")
        else:
            print(f"❌ {stage}: No data")
    
    print("=" * 60)


def main():
    parser = argparse.ArgumentParser(
        description="Stage Describe - Object Description & Room Style Analysis",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic usage
  python stage5_describe.py --image /path/to/image.png --scene-code /path/to/code.py
  
  # Use Memory (auto-get code)
  python stage5_describe.py --image /path/to/image.png
  
  # Show Memory status
  python stage5_describe.py --status
"""
    )
    
    parser.add_argument("--image", "-i", help="Reference image path")
    parser.add_argument("--scene-code", "-c", help="Scene code path")
    parser.add_argument("--output-dir", "-o", default=None, help="Output directory")
    parser.add_argument("--no-memory", action="store_true", help="Don't use Memory system")
    parser.add_argument("--status", "-s", action="store_true", help="Show Memory status")
    
    args = parser.parse_args()
    
    if args.status:
        show_memory_status()
        return 0
    
    if not args.image:
        parser.error("--image argument is required")
    
    runner = StageDescribeRunner(
        image_path=args.image,
        scene_code_path=args.scene_code,
        output_dir=args.output_dir,
        use_memory=not args.no_memory
    )
    
    success, result = runner.run()
    return 0 if success else 1


if __name__ == "__main__":
    exit(main())
