"""Stage2 runner script - Scene Graph construction
(v3.2: main graph strips minor + auto-derived against_wall + corner anchor)

Key changes (2026-05-02 v3.2):
- Building on v3.1, against_wall is now also auto-derived on the code side:
  when the LLM hint x_norm/y_norm is < 0.18 norm from any boundary, derive
  against_wall to the wall feat in that direction. Derivation order: against_wall -> corner.
  This compensates for the LLM frequently missing against_wall labels in stage2,
  letting stage3 trigger the [Floor Object Against-Wall Placement Rules] formula
  more reliably.
- When deriving against_wall, the corresponding wall feat is recorded in
  visual_reasoning; it is still deduped and will not duplicate against_wall
  edges already produced by the LLM.

Inherited from v3.1 (2026-05-02):
- 4 virtual corner anchor nodes corner_NE/NW/SE/SW
  (node_kind="architecture", arch_subtype="corner", is_virtual=True).
  Downstream stage6_geometry / stage12_render must skip them.
- Relations in_corner_<NE|NW|SE|SW> ↔ contains_corner_<NE|NW|SE|SW>:
  describe "object occupying a corner region" (leaving activity space; not requiring flush against the wall).
- Derivation rule: for each floor major object, if hint.centroid is biased
  toward both x and y boundaries (THRESH=0.30) and the type is not in the
  follower blacklist, derive in_corner_X. Objects that already have an
  against_wall edge are skipped (against_wall takes priority).

Inherited from v3 (2026-05-01) (unchanged):
1. The main scene graph (nodes/edges/zone_graphs/global_graph) only contains
   architecture + major objects; minor objects are not in the main graph.
2. Minor objects (with their parent relations) are output to a sidecar:
     - top-level minor_objects field of stage2_output.json
     - separate file stage2_minor_objects.json in the same directory
     - Memory metadata exposes minor_objects_count / minor_objects_json
3. The skeleton in the LLM prompt only shows major + architecture, saving output tokens.
4. The validator's expected id set excludes minor; minors in the main graph trigger a warning;
   the sidecar must cover all minors in stage1 (missing ones produce an error).

Inherited from v2 (unchanged):
- The node skeleton is derived directly from stage1 by code
- The LLM only fills visual_attributes/geometry_hint + forward edges
- Inverse edges are auto-generated by code
- zone_graphs / global_graph are derived by code
"""
import os
import sys
import json
import base64
import argparse
from typing import Any, Dict, List, Optional, Set, Tuple

current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
sys.path.insert(0, current_dir)
sys.path.insert(0, parent_dir)

from memory import Memory
from prompt_manager import PromptManager
from validators import validate_stage2_object_centric_schema, extract_json_from_response
from base import ValidationResult

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage


# ============================================================
# Module-level constants: inverse / direction / alignment flip tables
# ============================================================
INVERSE_RELATION_MAP: Dict[str, str] = {
    # position
    "north_of": "south_of", "south_of": "north_of",
    "east_of": "west_of", "west_of": "east_of",
    "north_east_of": "south_west_of", "south_west_of": "north_east_of",
    "north_west_of": "south_east_of", "south_east_of": "north_west_of",
    "overlapping": "overlapping",
    "partially_overlapping": "partially_overlapping",
    # distance (mostly symmetric)
    "touching": "touching", "adjacent_to": "adjacent_to",
    "near": "near", "far_from": "far_from",
    "separated_by_walkway": "separated_by_walkway",
    # alignment (symmetric)
    "aligned_left": "aligned_left", "aligned_right": "aligned_right",
    "aligned_top": "aligned_top", "aligned_bottom": "aligned_bottom",
    "aligned_center_x": "aligned_center_x", "aligned_center_y": "aligned_center_y",
    "in_same_row_as": "in_same_row_as", "in_same_column_as": "in_same_column_as",
    "parallel_to": "parallel_to", "perpendicular_to": "perpendicular_to",
    "centered_on": "centered_on",
    # support / containment
    "on_top_of": "supports", "supports": "on_top_of",
    "mounted_on": "supports",
    "inside": "contains", "contains": "inside",
    "under": "above", "above": "under",
    # functional
    "faces_for_use": "faces_for_use",
    "used_with": "used_with",
    "reachable_from": "reachable_from",
    "blocks_access_to": "blocks_access_to",
    "provides_clearance_for": "provides_clearance_for",
    # grouping
    "grouped_with": "grouped_with", "part_of_set": "part_of_set",
    "surrounds": "surrounded_by", "surrounded_by": "surrounds",
    "pairs_with": "pairs_with",
    # architecture
    "against_wall": "supports",
    "near_wall": "near_wall",
    "aligned_with_wall": "aligned_with_wall",
    "next_to_door": "next_to_door",
    "faces_opening": "faces_opening",
    "along_window": "along_window",
    # corner anchors (v3.1, 2026-05-02): object ↔ virtual corner anchor
    "in_corner_NE": "contains_corner_NE",
    "contains_corner_NE": "in_corner_NE",
    "in_corner_NW": "contains_corner_NW",
    "contains_corner_NW": "in_corner_NW",
    "in_corner_SE": "contains_corner_SE",
    "contains_corner_SE": "in_corner_SE",
    "in_corner_SW": "contains_corner_SW",
    "contains_corner_SW": "in_corner_SW",
}

DIRECTION_FLIP: Dict[str, str] = {
    "N": "S", "S": "N", "E": "W", "W": "E",
    "NE": "SW", "SW": "NE", "NW": "SE", "SE": "NW",
    "UNK": "UNK",
}

ALIGNMENT_FLIP: Dict[str, str] = {
    "left": "right", "right": "left",
    "top": "bottom", "bottom": "top",
    "center": "center", "none": "none", "unk": "unk",
}

LOCATION_NORM: Dict[str, str] = {
    "north": "N", "south": "S", "east": "E", "west": "W",
    "north_east": "NE", "north_west": "NW", "south_east": "SE", "south_west": "SW",
    "n": "N", "s": "S", "e": "E", "w": "W",
}


# ============================================================
# Node skeleton construction (derived from stage1, fully authoritative)
# ============================================================
def _normalize_location(loc: Optional[str]) -> str:
    if not loc:
        return ""
    raw = loc.strip().lower()
    key = raw.replace(" ", "_")
    direct = LOCATION_NORM.get(key)
    if direct:
        return direct
    # short codes like "n", "ne", "sw"
    if len(key) <= 3:
        return key.upper()
    # v3.2 fallback: search a long description for orientation keywords (e.g. "west boundary wall",
    # "north wall, eastern half") - prefer compound directions (NE/NW/SE/SW), then single directions.
    for compound, code in [
        ("north_east", "NE"), ("northeast", "NE"),
        ("north_west", "NW"), ("northwest", "NW"),
        ("south_east", "SE"), ("southeast", "SE"),
        ("south_west", "SW"), ("southwest", "SW"),
    ]:
        if compound in key:
            return code
    for single, code in [
        ("north", "N"), ("south", "S"), ("east", "E"), ("west", "W"),
    ]:
        if single in key:
            return code
    # v3.2 fallback for image-orientation phrasing ("top of image",
    # "bottom of image", "right of image", "left of image"). North = top
    # by image convention.
    for phrase, code in [
        ("top", "N"), ("bottom", "S"), ("right", "E"), ("left", "W"),
    ]:
        if phrase in key:
            return code
    return ""


def _build_node_skeleton(stage1_json: Dict) -> Dict[str, Any]:
    """Derive node skeleton from stage1 (v3.1: main graph contains major + architecture + corner anchors).

    Minor objects do not enter the main graph; they fall into the minor_records sidecar.

    Returns:
        {
            "nodes": [...],             # main-graph nodes (architecture + corner + major)
            "parent_edges_hint": [...], # main-graph support/mount edges (both ends in main graph)
            "arch_by_location": {...},  # "wall:north" -> "feat_001"
            "corner_by_dir": {...},     # "NE"/"NW"/"SE"/"SW" -> "corner_NE"/...
            "zone_meta": {...},         # zone_id -> {label, function}
            "minor_records": [...],     # sidecar: all minor objects + parent info
        }
    """
    nodes: List[Dict] = []
    arch_by_location: Dict[str, str] = {}
    zone_meta: Dict[str, Dict[str, str]] = {}

    # v3.1: 4 virtual corner anchor nodes (always injected, even when no objects derive in_corner_X;
    # stage3 / stage6_geometry must recognize is_virtual=True and skip geometry creation)
    corner_by_dir: Dict[str, str] = {}
    for dir_short, label_full in [
        ("NE", "Northeast corner anchor (virtual)"),
        ("NW", "Northwest corner anchor (virtual)"),
        ("SE", "Southeast corner anchor (virtual)"),
        ("SW", "Southwest corner anchor (virtual)"),
    ]:
        cid = f"corner_{dir_short}"
        corner_by_dir[dir_short] = cid
        nodes.append({
            "id": cid,
            "node_kind": "architecture",
            "label": label_full,
            "zone_id": "global",
            "type": "Fixed",
            "placement_type": "floor",
            "arch_subtype": "corner",
            "location": dir_short,
            "is_virtual": True,
        })

    # 1) architectural_features -> architecture nodes (reuse feat_xxx id)
    for feat in stage1_json.get("architectural_features", []) or []:
        fid = feat.get("feature_id")
        if not fid:
            continue
        ftype = (feat.get("feature_type") or "unknown").lower()
        loc_raw = feat.get("location") or ""
        loc_norm = _normalize_location(loc_raw)

        placement = "wall" if ftype in {"wall", "door", "window"} else "floor"
        nodes.append({
            "id": fid,
            "node_kind": "architecture",
            "label": (feat.get("description") or fid)[:120],
            "zone_id": "global",  # arch features do not belong to a specific zone
            "type": "Fixed",
            "placement_type": placement,
            "arch_subtype": ftype,
            "location": loc_norm,
        })
        if ftype == "wall" and loc_norm:
            # Support both "wall:north" and "wall:n" stage1 spellings
            arch_by_location[f"wall:{loc_raw.strip().lower()}"] = fid
            arch_by_location[f"wall:{loc_norm.lower()}"] = fid

    # 2) First pass: collect metadata for all stage1 objects (used in the
    #    minor sidecar to append parent_label / parent_placement_type fields
    #    for downstream consumers)
    obj_meta: Dict[str, Dict[str, Any]] = {}
    for zone in stage1_json.get("decoupled_zones", []) or []:
        zid = zone.get("zone_id")
        for obj in zone.get("object_hierarchy", []) or []:
            oid = obj.get("object_id")
            if not oid:
                continue
            obj_meta[oid] = {
                "name": obj.get("name", oid),
                "zone_id": zid,
                "placement_type": obj.get("placement_type") or "",
                "category": (obj.get("category") or "minor").lower(),
            }

    def _resolve_parent_id(parent_raw: Optional[str]) -> Optional[str]:
        """Normalize parent_object: obj_xxx / feat_xxx / wall:east / None."""
        if not isinstance(parent_raw, str) or not parent_raw:
            return None
        if parent_raw.startswith("obj_") or parent_raw.startswith("feat_"):
            return parent_raw
        if parent_raw.lower().startswith("wall:"):
            return arch_by_location.get(parent_raw.lower())
        return None

    # 3) Second pass: walk zones + object_hierarchy
    #    - major: enters main-graph nodes + parent_edges_hint
    #    - minor: only enters the minor_records sidecar, not the main graph
    parent_hints: List[Dict] = []
    minor_records: List[Dict] = []
    seen_obj_ids: Set[str] = set()
    for zone in stage1_json.get("decoupled_zones", []) or []:
        zid = zone.get("zone_id")
        if not zid:
            continue
        zone_meta[zid] = {
            "label": zone.get("zone_name", zid),
            "function": zone.get("primary_function", ""),
        }
        for obj in zone.get("object_hierarchy", []) or []:
            oid = obj.get("object_id")
            if not oid or oid in seen_obj_ids:
                continue
            seen_obj_ids.add(oid)

            cat = (obj.get("category") or "minor").lower()
            placement = obj.get("placement_type") or "floor"
            parent_id = _resolve_parent_id(obj.get("parent_object"))
            label = obj.get("name", oid)

            if cat != "major":
                # ---- minor goes to sidecar ----
                pmeta = obj_meta.get(parent_id) if parent_id else None
                minor_records.append({
                    "id": oid,
                    "label": label,
                    "zone_id": zid,
                    "placement_type": placement,
                    "category": cat,
                    "parent_id": parent_id,
                    "parent_label": (pmeta or {}).get("name") if pmeta else None,
                    "parent_placement_type": (
                        (pmeta or {}).get("placement_type") if pmeta else None
                    ),
                    "parent_category": (
                        (pmeta or {}).get("category") if pmeta else None
                    ),
                    # When parent is not in obj_meta but resolvable via arch_by_location, mark it
                    "parent_kind": (
                        "architecture"
                        if (parent_id and parent_id.startswith("feat_"))
                        else ("object" if parent_id else None)
                    ),
                })
                continue

            # ---- major: enters main graph ----
            nodes.append({
                "id": oid,
                "node_kind": "object",
                "label": label,
                "zone_id": zid,
                "type": "Major",
                "placement_type": placement,
                "parent_id": parent_id,  # internal-only, removed during merge
            })

            # Derive parent->child support / mount edges (both ends must be in the main graph)
            if not parent_id:
                continue
            parent_in_main = (
                parent_id.startswith("feat_")
                or (obj_meta.get(parent_id, {}).get("category") == "major")
            )
            if not parent_in_main:
                continue
            if placement == "wall":
                rel = "mounted_on"
            elif placement == "surface":
                rel = "on_top_of"
            else:
                rel = None
            if rel:
                parent_hints.append({
                    "source": oid, "target": parent_id, "relation": rel,
                })

    return {
        "nodes": nodes,
        "parent_edges_hint": parent_hints,
        "arch_by_location": arch_by_location,
        "corner_by_dir": corner_by_dir,
        "zone_meta": zone_meta,
        "minor_records": minor_records,
    }


# ============================================================
# Helpers: scope / categorization / inverse edge generation
# ============================================================
def _build_node_lookup(nodes: List[Dict]) -> Dict[str, Dict]:
    return {n["id"]: n for n in nodes if "id" in n}


def _decide_scope(node_lookup: Dict[str, Dict], sid: str, tid: str) -> str:
    s = node_lookup.get(sid)
    t = node_lookup.get(tid)
    if not s or not t:
        return "intra_zone"
    if s.get("node_kind") == "architecture" or t.get("node_kind") == "architecture":
        return "object_to_architecture"
    if s.get("zone_id") == t.get("zone_id"):
        return "intra_zone"
    return "inter_zone"


def _decide_category(rel: str) -> str:
    pos = {"north_of", "south_of", "east_of", "west_of", "north_east_of",
           "north_west_of", "south_east_of", "south_west_of",
           "overlapping", "partially_overlapping"}
    dist = {"touching", "adjacent_to", "near", "far_from", "separated_by_walkway"}
    align = {"aligned_left", "aligned_right", "aligned_top", "aligned_bottom",
             "aligned_center_x", "aligned_center_y", "in_same_row_as",
             "in_same_column_as", "parallel_to", "perpendicular_to", "centered_on"}
    sup = {"on_top_of", "supports", "mounted_on", "under", "above"}
    cont = {"inside", "contains"}
    func = {"faces_for_use", "used_with", "reachable_from",
            "blocks_access_to", "provides_clearance_for"}
    grp = {"grouped_with", "part_of_set", "surrounds", "surrounded_by", "pairs_with"}
    arch = {"against_wall", "near_wall", "aligned_with_wall",
            "next_to_door", "faces_opening", "along_window",
            "in_corner_NE", "in_corner_NW", "in_corner_SE", "in_corner_SW",
            "contains_corner_NE", "contains_corner_NW",
            "contains_corner_SE", "contains_corner_SW"}

    if rel in pos: return "position"
    if rel in dist: return "distance"
    if rel in align: return "alignment"
    if rel in sup: return "support"
    if rel in cont: return "containment"
    if rel in func: return "functional"
    if rel in grp: return "grouping"
    if rel in arch: return "architecture"
    return "position"


# ============================================================
# v3.2: against_wall derivation (code side, no LLM dependency)
# ============================================================
# The stage2 LLM frequently misses against_wall labels (especially when objects are not very close to the image edge).
# Here, based on the LLM-provided hint.centroid, when the norm distance to any boundary is < THRESH,
# derive against_wall to the wall feat in that direction. Derivation order is before corner,
# so corner derivation can correctly "skip objects that already have against_wall".
#
# Note: hint is the object center, not its edge, so the threshold is a bit lenient (covers the LLM's
# systematic 0.05~0.10 norm inward bias). Also only derive for placement_type=floor Major objects;
# do not derive for surface / wall objects (those are handled by parent edges).
_WALL_HINT_THRESH: float = 0.22  # norm distance: center within 0.22 of the wall counts as against the wall

# "Non-flush" blacklist: even if hint is near a wall, do not derive against_wall for these types.
# (chairs around tables, dining/coffee tables in the room center, lamps/plants placed freely as decoration)
# Note: nightstand / dresser / bookcase / sideboard etc. are NOT in this list -
# they should be allowed to derive against_wall.
_WALL_NONFLUSH_KEYWORDS: Tuple[str, ...] = (
    # exclude all chairs (lounge / armchair are also free-standing, not against the wall)
    "chair", "armchair", "stool", "ottoman", "bench", "seat",
    # tables (except desk, which is still an against-wall candidate - desk is not in this list)
    "dining table", "dining_table",
    "coffee table", "coffee_table",
    "side table", "side_table", "end table", "end_table",
    "round table", "round_table",
    # decoration
    "lamp", "lantern", "plant", "planter", "pot", "potted",
    "rug", "carpet", "mat",
)


def _is_wall_nonflush(label: Optional[str]) -> bool:
    if not label:
        return False
    s = label.lower()
    return any(k in s for k in _WALL_NONFLUSH_KEYWORDS)


def _derive_wall_edges(
    skeleton: Dict[str, Any],
    llm_attrs: Dict[str, Dict],
    existing_wall_pairs: Set[Tuple[str, str]],
) -> List[Dict]:
    """Derive against_wall edges to the wall feat in the corresponding direction based on hint.centroid.

    Args:
        skeleton: output of _build_node_skeleton.
        llm_attrs: LLM-output node_attributes (with geometry_hint).
        existing_wall_pairs: against_wall (sid, tid) pairs already present in
            LLM forward edges, used for dedup.

    Returns:
        forward edge list (against_wall); the caller is responsible for adding edge_id and inverse edges.
    """
    arch_by_loc = skeleton.get("arch_by_location") or {}
    if not arch_by_loc:
        return []

    # Index: short direction -> wall feat id (fallback)
    # In _build_node_skeleton, location is already normalized to N/S/E/W via _normalize_location,
    # but arch_by_location keys use lowercase ("wall:n" etc.), so look up with lowercase here;
    # also try long form ("wall:north" etc.) as a fallback.
    dir_to_wall: Dict[str, str] = {}
    long_form = {"N": "north", "S": "south", "E": "east", "W": "west"}
    for d in ("N", "S", "E", "W"):
        fid = (arch_by_loc.get(f"wall:{d.lower()}") or
               arch_by_loc.get(f"wall:{long_form[d]}"))
        if fid:
            dir_to_wall[d] = fid

    if not dir_to_wall:
        return []

    out: List[Dict] = []
    for n in skeleton["nodes"]:
        if n.get("node_kind") != "object":
            continue
        if n.get("type") != "Major":
            continue
        if n.get("placement_type") != "floor":
            continue
        if _is_wall_nonflush(n.get("label")):
            continue
        oid = n["id"]

        a = (llm_attrs or {}).get(oid) or {}
        gh = a.get("geometry_hint") or {}
        c = gh.get("centroid") if isinstance(gh, dict) else None
        if not isinstance(c, dict):
            continue
        x = c.get("x_norm")
        y = c.get("y_norm")
        if not (isinstance(x, (int, float)) and isinstance(y, (int, float))):
            continue
        x = float(x); y = float(y)

        # Distance to the 4 walls (image convention: y=0 is N at top)
        dists = {
            "W": x,
            "E": 1.0 - x,
            "N": y,
            "S": 1.0 - y,
        }
        # Pick the closest one (and < THRESH)
        best_dir, best_d = min(dists.items(), key=lambda kv: kv[1])
        if best_d > _WALL_HINT_THRESH:
            continue
        wall_id = dir_to_wall.get(best_dir)
        if not wall_id:
            continue
        if (oid, wall_id) in existing_wall_pairs:
            continue  # already produced by the LLM, do not duplicate

        out.append({
            "source": oid,
            "target": wall_id,
            "relation": "against_wall",
            "relation_category": "architecture",
            "scope": "object_to_architecture",
            "spatial_signature": {
                "direction_8": best_dir,
                "overlap": {"type": "none"},
                "alignment": {"x": "none", "y": "none"},
            },
            "visual_reasoning": (
                f"Auto-derived: hint centroid ({x:.2f}, {y:.2f}) sits "
                f"{best_d:.2f} norm from the {best_dir} wall (< "
                f"{_WALL_HINT_THRESH:.2f}); flush against {wall_id}."
            ),
            "_derived_wall": True,
        })
    return out


# ============================================================
# v3.1: corner anchor derivation (code side, no LLM dependency)
# ============================================================
# "Anchor candidate" blacklist: these types are mostly followers and should not be tagged in_corner_X.
# Match rule: lowercase label substring.
#
# Design notes (v3.1):
# - Surrounding chairs (dining chair / office chair / side chair) -> follower, excluded
# - Nightstand / side table / floor lamp / decoration -> follower, excluded
# - Sofa-style seats (lounge armchair / wing chair / club chair / accent chair)
#   are seats that can "stand on their own" and form a zone in a room corner -> allowed as anchor
# - "armchair" used alone usually means accent / lounge -> also allowed as anchor
_CORNER_FOLLOWER_KEYWORDS: Tuple[str, ...] = (
    # surrounding chairs: dragged along by anchors like dining table / desk
    "dining chair", "dining_chair",
    "office chair", "office_chair", "desk chair", "desk_chair",
    "side chair", "side_chair",
    "stool", "bar stool", "counter stool", "bench",
    # bed-adjacent followers
    "nightstand", "night stand", "night_stand",
    # side / corner tables (followers themselves rather than corner anchors)
    "side table", "side_table", "end table", "end_table",
    # decoration / lamps / textiles
    "lamp", "lantern", "sconce",
    "cushion", "pillow", "throw", "blanket",
    "vase", "plant", "planter", "pot ", "pot,", "potted",
    "rug", "carpet", "mat",
    "tray", "decanter", "bottle", "candle", "frame", "art piece",
    "basket", "bookend", "ornament", "sculpture", "figurine",
)

# How close the object hint must be to a boundary to count as "against that side" (between 0 and 0.5)
# 0.30 means x_norm < 0.30 counts as against W, > 0.70 counts as against E (Y similarly).
_CORNER_THRESH: float = 0.30


def _is_corner_follower(label: Optional[str]) -> bool:
    if not label:
        return False
    s = label.lower()
    return any(k in s for k in _CORNER_FOLLOWER_KEYWORDS)


def _classify_corner(x_norm: float, y_norm: float) -> Optional[str]:
    """Decide corner direction from a normalized centroid (image convention: y=0 is N).

    Returns: "NE" / "NW" / "SE" / "SW" or None (not in any corner).
    """
    near_w = x_norm < _CORNER_THRESH
    near_e = x_norm > 1.0 - _CORNER_THRESH
    near_n = y_norm < _CORNER_THRESH
    near_s = y_norm > 1.0 - _CORNER_THRESH
    if near_n and near_e:
        return "NE"
    if near_n and near_w:
        return "NW"
    if near_s and near_e:
        return "SE"
    if near_s and near_w:
        return "SW"
    return None


def _derive_corner_edges(
    skeleton: Dict[str, Any],
    llm_attrs: Dict[str, Dict],
    existing_wall_targets: Set[str],
) -> List[Dict]:
    """Derive in_corner_<X> edges from stage1/LLM-provided geometry_hint.

    Args:
        skeleton: output of _build_node_skeleton.
        llm_attrs: LLM-output node_attributes (with geometry_hint, if any).
        existing_wall_targets: source id set already appearing as against_wall
            in LLM forward edges - those objects skip derivation (avoid double anchoring).

    Returns:
        forward edge list (in_corner_X), in the same shape as other forward edges in
        _merge_skeleton_with_llm; the caller is responsible for adding edge_id and inverse edges.
    """
    corner_by_dir = skeleton.get("corner_by_dir") or {}
    if not corner_by_dir:
        return []

    out: List[Dict] = []
    for n in skeleton["nodes"]:
        # Only floor major objects (no architecture, no minor that has been split off)
        if n.get("node_kind") != "object":
            continue
        if n.get("type") != "Major":
            continue
        if n.get("placement_type") != "floor":
            continue
        oid = n["id"]
        if oid in existing_wall_targets:
            # Already tagged against_wall by the LLM -> do not derive in_corner (semantic conflict)
            continue
        if _is_corner_follower(n.get("label")):
            continue

        # geometry_hint comes from LLM output first (it has visual judgment), falling back to stage1
        # (but stage1 hints are not on skeleton nodes during v3 derivation, so we can only use what the LLM gives us)
        a = (llm_attrs or {}).get(oid) or {}
        gh = a.get("geometry_hint") or {}
        c = gh.get("centroid") if isinstance(gh, dict) else None
        if not isinstance(c, dict):
            continue
        x = c.get("x_norm")
        y = c.get("y_norm")
        if not (isinstance(x, (int, float)) and isinstance(y, (int, float))):
            continue
        corner_dir = _classify_corner(float(x), float(y))
        if not corner_dir:
            continue
        cid = corner_by_dir.get(corner_dir)
        if not cid:
            continue
        rel = f"in_corner_{corner_dir}"
        out.append({
            "source": oid,
            "target": cid,
            "relation": rel,
            "relation_category": "architecture",
            "scope": "object_to_architecture",
            "spatial_signature": {
                "direction_8": corner_dir,
                "overlap": {"type": "none"},
                "alignment": {"x": "none", "y": "none"},
            },
            "visual_reasoning": (
                f"Auto-derived: hint centroid ({x:.2f}, {y:.2f}) sits in "
                f"the {corner_dir} corner region (>= {1-_CORNER_THRESH:.2f} or "
                f"<= {_CORNER_THRESH:.2f} on both axes)."
            ),
            "_derived_corner": True,
        })
    return out


def _make_inverse_edge(edge: Dict) -> Optional[Dict]:
    rel = edge.get("relation")
    if not rel:
        return None
    inv_rel = INVERSE_RELATION_MAP.get(rel)
    if not inv_rel:
        return None

    sig = edge.get("spatial_signature") or {}
    inv_sig = {
        "direction_8": DIRECTION_FLIP.get(sig.get("direction_8", "UNK"), "UNK"),
        "overlap": sig.get("overlap") or {"type": "none"},
        "alignment": {
            "x": ALIGNMENT_FLIP.get((sig.get("alignment") or {}).get("x", "none"), "none"),
            "y": ALIGNMENT_FLIP.get((sig.get("alignment") or {}).get("y", "none"), "none"),
        },
    }
    return {
        "source": edge["target"],
        "target": edge["source"],
        "relation": inv_rel,
        "relation_category": edge.get("relation_category") or _decide_category(inv_rel),
        "scope": edge.get("scope"),
        "spatial_signature": inv_sig,
        "visual_reasoning": f"Auto inverse of {edge['source']} -({rel})-> {edge['target']}.",
        "_auto_generated": True,
    }


# ============================================================
# Merge: skeleton + LLM output -> final stage2 JSON
# ============================================================
def _merge_skeleton_with_llm(skeleton: Dict, llm_out: Dict) -> Dict:
    """Combine the code-side skeleton + LLM node_attributes/edges into the final stage2 JSON.

    Output schema (v3): meta / zone_relations / nodes / edges /
    zone_graphs / global_graph / minor_objects

    minor_objects is a sidecar from skeleton["minor_records"], not part of the graph,
    consumed by downstream stage4 (coarse placement) and stage7_small_objects (collision avoidance).
    """
    skel_nodes = skeleton["nodes"]
    parent_hints = skeleton["parent_edges_hint"]
    zone_meta = skeleton["zone_meta"]
    minor_records: List[Dict] = skeleton.get("minor_records", []) or []
    attrs: Dict[str, Dict] = (llm_out or {}).get("node_attributes") or {}

    # 1) Merge nodes: skeleton fields are immutable; only append visual_attributes/geometry_hint
    final_nodes: List[Dict] = []
    for n in skel_nodes:
        a = attrs.get(n["id"]) or {}
        merged = {k: v for k, v in n.items() if k != "parent_id"}
        va = a.get("visual_attributes") or []
        if isinstance(va, list):
            merged["visual_attributes"] = [str(x) for x in va][:8]
        else:
            merged["visual_attributes"] = []
        if isinstance(a.get("geometry_hint"), dict):
            merged["geometry_hint"] = a["geometry_hint"]
        final_nodes.append(merged)

    node_lookup = _build_node_lookup(final_nodes)
    valid_ids = set(node_lookup.keys())

    # 2) Collect forward edges: parent_hints + LLM edges
    forward: List[Dict] = []
    seen_keys: Set[Tuple[str, str, str]] = set()

    for p in parent_hints:
        sid, tid, rel = p["source"], p["target"], p["relation"]
        if sid not in valid_ids or tid not in valid_ids:
            continue
        key = (sid, tid, rel)
        if key in seen_keys:
            continue
        seen_keys.add(key)
        forward.append({
            "source": sid, "target": tid, "relation": rel,
            "relation_category": _decide_category(rel),
            "scope": _decide_scope(node_lookup, sid, tid),
            "spatial_signature": {
                "direction_8": "UNK",
                "overlap": {"type": "full" if rel == "on_top_of" else "none"},
                "alignment": {"x": "center", "y": "center"},
            },
            "visual_reasoning": "Parent relation derived from Stage1 hierarchy.",
            "_from_skeleton": True,
        })

    for e in (llm_out or {}).get("edges", []) or []:
        sid = e.get("source"); tid = e.get("target"); rel = e.get("relation")
        if not (sid and tid and rel):
            continue
        if sid not in valid_ids or tid not in valid_ids:
            continue  # drop edges that reference non-existent ids (validator will still warn)
        if sid == tid:
            continue
        if rel not in INVERSE_RELATION_MAP:
            continue
        key = (sid, tid, rel)
        if key in seen_keys:
            continue
        seen_keys.add(key)
        sig = e.get("spatial_signature") or {}
        forward.append({
            "source": sid, "target": tid, "relation": rel,
            "relation_category": e.get("relation_category") or _decide_category(rel),
            "scope": e.get("scope") or _decide_scope(node_lookup, sid, tid),
            "spatial_signature": {
                "direction_8": sig.get("direction_8", "UNK"),
                "overlap": sig.get("overlap") or {"type": "none"},
                "alignment": sig.get("alignment") or {"x": "none", "y": "none"},
            },
            "visual_reasoning": (e.get("visual_reasoning") or "")[:200],
        })

    # 2.4) v3.2: code-side derivation of against_wall edges (based on hint thresholds)
    #     - Injected after LLM edges, before corner derivation
    #     - This way corner derivation sees against_wall including the derived items
    existing_wall_pairs: Set[Tuple[str, str]] = {
        (fe["source"], fe["target"]) for fe in forward
        if fe.get("relation") == "against_wall"
    }
    derived_wall = _derive_wall_edges(skeleton, attrs, existing_wall_pairs)
    for fe in derived_wall:
        sid, tid, rel = fe["source"], fe["target"], fe["relation"]
        if sid not in valid_ids or tid not in valid_ids:
            continue
        key = (sid, tid, rel)
        if key in seen_keys:
            continue
        seen_keys.add(key)
        forward.append(fe)

    # 2.5) v3.1: code-side derivation of corner anchor edges (in_corner_<NE|NW|SE|SW>)
    #     - Injected after LLM edges and against_wall derivation: skip objects that already have against_wall
    #     - Decided via the LLM's geometry_hint (prioritize the LLM's visual judgment)
    #     - (sid, tid, rel) already tagged in_corner_* by the LLM is in seen_keys, so no duplicates
    against_wall_sources: Set[str] = {
        fe["source"] for fe in forward
        if fe.get("relation") == "against_wall"
    }
    derived_corner = _derive_corner_edges(skeleton, attrs, against_wall_sources)
    for fe in derived_corner:
        sid, tid, rel = fe["source"], fe["target"], fe["relation"]
        if sid not in valid_ids or tid not in valid_ids:
            continue
        key = (sid, tid, rel)
        if key in seen_keys:
            continue
        seen_keys.add(key)
        forward.append(fe)

    # 3) Auto-derive inverse edges
    all_edges: List[Dict] = []
    edge_idx = 1
    for fe in forward:
        eid = f"e_{edge_idx:04d}"
        edge_idx += 1
        all_edges.append({**fe, "edge_id": eid})

        inv = _make_inverse_edge(fe)
        if not inv:
            continue
        inv_key = (inv["source"], inv["target"], inv["relation"])
        if inv_key in seen_keys:
            continue
        seen_keys.add(inv_key)
        inv_eid = f"e_{edge_idx:04d}"
        edge_idx += 1
        all_edges.append({**inv, "edge_id": inv_eid})

    # 4) zone_graphs: group by zone_id (skip global)
    zone_to_nodes: Dict[str, List[str]] = {}
    for n in final_nodes:
        zid = n["zone_id"]
        zone_to_nodes.setdefault(zid, []).append(n["id"])

    zone_graphs: List[Dict] = []
    for zid in sorted(k for k in zone_to_nodes.keys() if k != "global"):
        nids = zone_to_nodes[zid]
        nid_set = set(nids)
        eids = [e["edge_id"] for e in all_edges
                if e["source"] in nid_set and e["target"] in nid_set]
        zone_graphs.append({
            "zone_id": zid,
            "zone_label": zone_meta.get(zid, {}).get("label", zid),
            "zone_function": zone_meta.get(zid, {}).get("function", ""),
            "node_ids": nids,
            "edge_ids": eids,
        })

    # 5) global_graph: all nodes + all edges
    global_graph = {
        "node_ids": [n["id"] for n in final_nodes],
        "edge_ids": [e["edge_id"] for e in all_edges],
    }

    meta = (llm_out or {}).get("meta") or {}
    meta.setdefault("stage", "stage2_object_centric_graph")
    meta.setdefault("north_is", "up")
    meta.setdefault("notes", "Code-injected nodes; auto-generated inverse edges.")
    meta["main_graph_scope"] = "major_and_architecture_only"
    meta["minor_objects_count"] = len(minor_records)

    return {
        "meta": meta,
        "zone_relations": (llm_out or {}).get("zone_relations") or [],
        "nodes": final_nodes,
        "edges": all_edges,
        "zone_graphs": zone_graphs,
        "global_graph": global_graph,
        "minor_objects": minor_records,
    }


# ============================================================
# Stage2Runner
# ============================================================
class Stage2Runner:
    """Stage2 runner - Scene Graph construction (v2)."""

    def __init__(
        self,
        image_path: str = None,
        output_dir: str = "./output",
        max_iterations: int = 3,
        verbose: bool = True,
        model: str = None,
        base_url: str = None,
        api_key: str = None,
        memory_file: str = "agent_memory.jsonl",
        max_tokens: int = 65536,
    ):
        self.image_path = image_path
        self.output_dir = output_dir
        self.max_iterations = max_iterations
        self.verbose = verbose

        self.llm = ChatOpenAI(
            model=model or os.environ.get("SCENEGEN_MODEL") or "gemini-3.5-flash",
            base_url=(
                base_url
                or os.environ.get("SCENEGEN_BASE_URL")
                or os.environ.get("GEMINI_BASE_URL")
                or "https://generativelanguage.googleapis.com/v1beta/openai/"
            ),
            api_key=(
                api_key
                or os.environ.get("SCENEGEN_API_KEY")
                or os.environ.get("GEMINI_API_KEY")
                or os.environ.get("OPENAI_API_KEY")
            ),
            temperature=1,
            max_tokens=max_tokens,
            timeout=600,
            request_timeout=600,
            max_retries=3,
        )

        self.memory = Memory(workspace_dir=parent_dir, memory_file=memory_file)
        self.prompts = PromptManager()
        self.task_prompt = self.prompts.get("Stage2_task")
        self.fix_template = self.prompts.get("Stage2_fix_template")

        self.stage1_json: Optional[Dict] = None
        self.skeleton: Optional[Dict] = None
        self.current_output: Optional[str] = None      # raw LLM string
        self.parsed_llm: Optional[Dict] = None         # parsed LLM JSON
        self.parsed_json: Optional[Dict] = None        # final merged JSON
        self.iteration = 0

    def _log(self, msg: str, level: str = "info"):
        if self.verbose:
            prefix = {"info": "ℹ️", "success": "✅", "warning": "⚠️",
                      "error": "❌", "step": "📋"}.get(level, "")
            print(f"{prefix} {msg}")

    def _encode_image(self, path: str) -> tuple:
        with open(path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("utf-8")
        ext = os.path.splitext(path)[1].lower()
        mime = {".jpg": "image/jpeg", ".jpeg": "image/jpeg",
                ".png": "image/png"}.get(ext, "image/png")
        return b64, mime

    def _load_stage1(self) -> bool:
        self._log("Fetching Stage1 result from Memory...", "step")
        entry = self.memory.get_latest(stage="stage1", type="result")
        if not entry:
            self._log("No Stage1 result in Memory!", "error")
            return False
        self.stage1_json = entry.content
        if not self.image_path:
            self.image_path = entry.metadata.get("image_path")
        self._log("Stage1 fetched", "success")
        return True

    def _build_skeleton_prompt_payload(self) -> str:
        """Build a compact skeleton for the LLM (save tokens)."""
        nodes = self.skeleton["nodes"]
        rows = []
        for n in nodes:
            row = {
                "id": n["id"],
                "kind": n["node_kind"],
                "zone": n["zone_id"],
                "type": n["type"],
                "placement": n["placement_type"],
                "label": n["label"],
            }
            if n.get("parent_id"):
                row["parent"] = n["parent_id"]
            if n.get("location"):
                row["location"] = n["location"]
            if n.get("arch_subtype"):
                row["arch_subtype"] = n["arch_subtype"]
            rows.append(row)
        return json.dumps(rows, ensure_ascii=False)

    def _generate(self, fix_instructions: str = None) -> Optional[str]:
        self._log(f"Generating JSON (iter {self.iteration}/{self.max_iterations})", "step")

        system_content = self.task_prompt
        if fix_instructions:
            system_content += f"\n\n[Fix requirements]\n{fix_instructions}"

        skeleton_payload = self._build_skeleton_prompt_payload()
        zone_summary = [
            {"zone_id": z["zone_id"], "name": z.get("zone_name", ""),
             "function": z.get("primary_function", "")}
            for z in self.stage1_json.get("decoupled_zones", []) or []
        ]
        scene_dim = (self.stage1_json.get("scene_scale_understanding") or {})

        minor_count = len(self.skeleton.get("minor_records", []) or [])
        user_text = (
            "Stage1 skeleton injected (main graph contains only architecture + major objects, "
            f"{minor_count} minor objects already split off).\n"
            "You only need to output node_attributes and forward edges (for nodes in the skeleton).\n"
            "Do not reference any id in edges that is not in node_skeleton; "
            "minor objects are handled separately by downstream stages and are ignored here.\n\n"
            f"[scene_scale]\n{json.dumps(scene_dim, ensure_ascii=False)}\n\n"
            f"[zones]\n{json.dumps(zone_summary, ensure_ascii=False)}\n\n"
            f"[node_skeleton]\n{skeleton_payload}\n"
        )
        if fix_instructions:
            user_text = f"Re-emit after fixing the following issues:\n{fix_instructions}\n\n" + user_text

        if self.image_path and os.path.exists(self.image_path):
            b64, mime = self._encode_image(self.image_path)
            messages = [
                SystemMessage(content=system_content),
                HumanMessage(content=[
                    {"type": "image_url",
                     "image_url": {"url": f"data:{mime};base64,{b64}"}},
                    {"type": "text", "text": user_text},
                ]),
            ]
        else:
            messages = [SystemMessage(content=system_content),
                        HumanMessage(content=user_text)]

        import time as _time
        max_api_retries = 5
        for attempt in range(1, max_api_retries + 1):
            try:
                response = self.llm.invoke(messages)
                json_str = extract_json_from_response(response.content)
                self.current_output = json_str
                self._log(f"Generation finished ({len(json_str)} chars)", "success")
                return json_str
            except Exception as e:
                err_str = str(e)
                is_retryable = any(k in err_str for k in (
                    "502", "503", "429", "Connection error",
                    "upstream", "timeout", "Timeout"))
                if is_retryable and attempt < max_api_retries:
                    wait = min(10 * attempt, 60)
                    self._log(f"API error (attempt {attempt}/{max_api_retries}): "
                              f"{e} - retrying in {wait}s", "warning")
                    _time.sleep(wait)
                    continue
                self._log(f"Generation failed: {e}", "error")
                import traceback
                traceback.print_exc()
                return None

    def _validate(self) -> ValidationResult:
        self._log("Parsing LLM output + merging skeleton...")

        try:
            self.parsed_llm = json.loads(self.current_output)
        except json.JSONDecodeError as e:
            return ValidationResult(is_valid=False, errors=[f"JSON parse error: {e}"])

        try:
            self.parsed_json = _merge_skeleton_with_llm(self.skeleton, self.parsed_llm)
        except Exception as e:
            return ValidationResult(is_valid=False, errors=[f"Merge failed: {e}"])

        result = validate_stage2_object_centric_schema(
            self.parsed_json, stage1_json=self.stage1_json)

        if result.is_valid:
            self._log(f"Validation passed (warnings={len(result.warnings)})", "success")
        else:
            self._log(f"Validation failed: {len(result.errors)} errors", "error")
        return result

    def _generate_fix_instructions(self, validation_result: ValidationResult) -> str:
        errors_text = "\n".join(f"- {e}" for e in validation_result.errors[:30])
        snippet = (self.current_output[:1500] + "...") \
            if len(self.current_output) > 1500 else self.current_output
        try:
            fix_prompt = self.fix_template.format(
                errors=errors_text, current_json=snippet)
        except Exception:
            fix_prompt = errors_text
        try:
            response = self.llm.invoke([
                SystemMessage(content="You are a JSON Schema repair expert"),
                HumanMessage(content=fix_prompt),
            ])
            return response.content.strip()
        except Exception:
            return errors_text

    def _save_to_memory(self):
        if not self.parsed_json:
            return
        nodes = self.parsed_json.get("nodes", [])
        edges = self.parsed_json.get("edges", [])
        zone_graphs = self.parsed_json.get("zone_graphs", [])
        minors = self.parsed_json.get("minor_objects", []) or []
        title = (f"{len(zone_graphs)} zones, {len(nodes)} main-graph nodes, "
                 f"{len(edges)} relations, {len(minors)} minor")

        # sidecar file path (written uniformly in _save_files; only exposing the path here)
        minor_json_path = os.path.join(self.output_dir, "stage2_minor_objects.json")

        self.memory.add(
            stage="stage2", type="result", content=self.parsed_json,
            metadata={
                "success": True, "title": title,
                "summary": f"{len(zone_graphs)} zones (skeleton-aligned, main graph major-only)",
                "iterations": self.iteration, "image_path": self.image_path,
                "main_graph_scope": "major_and_architecture_only",
                "minor_objects_count": len(minors),
                "minor_objects_json": minor_json_path,
            },
            tags=["stage2", "success"],
        )
        self._log(f"Saved to Memory: {title}", "success")

        # Also store the minor sidecar as a separate Memory entry for easy downstream querying
        if minors:
            self.memory.add(
                stage="stage2", type="minor_objects",
                content={"minor_objects": minors},
                metadata={
                    "title": f"Stage2 minor sidecar ({len(minors)} items)",
                    "minor_objects_count": len(minors),
                    "minor_objects_json": minor_json_path,
                    "image_path": self.image_path,
                },
                tags=["stage2", "minor_objects", "sidecar"],
            )

    def _save_files(self):
        os.makedirs(self.output_dir, exist_ok=True)
        if self.parsed_json:
            path = os.path.join(self.output_dir, "stage2_output.json")
            with open(path, "w", encoding="utf-8") as f:
                json.dump(self.parsed_json, f, ensure_ascii=False, indent=2)
            self._log(f"JSON: {path}")

            # minor sidecar separate file (written even when empty for unified downstream reads)
            minors = self.parsed_json.get("minor_objects", []) or []
            sidecar_path = os.path.join(
                self.output_dir, "stage2_minor_objects.json")
            with open(sidecar_path, "w", encoding="utf-8") as f:
                json.dump({
                    "stage": "stage2",
                    "image_path": self.image_path,
                    "count": len(minors),
                    "minor_objects": minors,
                }, f, ensure_ascii=False, indent=2)
            self._log(f"Minor sidecar: {sidecar_path} ({len(minors)} items)")

        if self.current_output:
            path = os.path.join(self.output_dir, "stage2_raw.txt")
            with open(path, "w", encoding="utf-8") as f:
                f.write(self.current_output)
            self._log(f"Raw: {path}")
        if self.skeleton:
            path = os.path.join(self.output_dir, "stage2_skeleton.json")
            with open(path, "w", encoding="utf-8") as f:
                json.dump(self.skeleton, f, ensure_ascii=False, indent=2)
            self._log(f"Skeleton: {path}")

    def run(self) -> tuple:
        print("\n" + "=" * 60)
        print("Stage2 - Scene Graph construction)")
        print("=" * 60)

        if not self._load_stage1():
            return False, None, {}

        # Build skeleton (code is authoritative)
        try:
            self.skeleton = _build_node_skeleton(self.stage1_json)
        except Exception as e:
            self._log(f"Skeleton build failed: {e}", "error")
            return False, None, {}
        self._log(
            f"Skeleton: {len(self.skeleton['nodes'])} main-graph nodes (major+arch), "
            f"{len(self.skeleton['parent_edges_hint'])} parent-child edges, "
            f"{len(self.skeleton.get('minor_records', []) or [])} minor (sidecar)",
            "success",
        )

        if self.image_path:
            self._log(f"Image: {self.image_path}")

        fix_instructions = None
        for self.iteration in range(1, self.max_iterations + 1):
            print(f"\n{'─' * 40}")
            self._log(f"Iteration {self.iteration}/{self.max_iterations}", "step")
            print(f"{'─' * 40}")

            output = self._generate(fix_instructions)
            if not output:
                continue

            validation = self._validate()
            if validation.is_valid:
                self._save_to_memory()
                self._save_files()
                print("\n" + "=" * 60)
                print("[OK] Stage2 done!")
                print("=" * 60)
                return True, self.parsed_json, {"iterations": self.iteration}

            if self.iteration < self.max_iterations:
                fix_instructions = self._generate_fix_instructions(validation)

        self._log("Reached maximum iterations", "warning")
        self._save_files()
        return False, self.parsed_json, {"iterations": self.iteration}


# ============================================================
# CLI entry point
# ============================================================
def show_memory_status():
    memory = Memory(workspace_dir=os.path.dirname(
        os.path.dirname(os.path.abspath(__file__))))
    print("=" * 60)
    print("[>] Memory status")
    print("=" * 60)
    for stage in ["stage1", "stage2"]:
        entry = memory.get_latest(stage=stage, type="result")
        if entry:
            title = entry.metadata.get("title", "untitled")
            from datetime import datetime
            time_str = datetime.fromtimestamp(entry.timestamp).strftime("%m-%d %H:%M")
            print(f"✅ {stage}: {title} ({time_str})")
        else:
            print(f"[X] {stage}: no data")
    print("=" * 60)


def main():
    parser = argparse.ArgumentParser(description="Stage2 - Scene Graph construction (v2)")
    parser.add_argument("--image", "-i", help="Image path")
    parser.add_argument("--output-dir", "-o", default="./output", help="Output directory")
    parser.add_argument("--max-iter", "-n", type=int, default=3, help="Maximum iterations")
    parser.add_argument("--max-tokens", type=int, default=65536, help="LLM max_tokens")
    parser.add_argument("--quiet", "-q", action="store_true", help="Quiet mode")
    parser.add_argument("--status", "-s", action="store_true", help="Show Memory")
    args = parser.parse_args()

    if args.status:
        show_memory_status()
        return 0

    runner = Stage2Runner(
        image_path=args.image, output_dir=args.output_dir,
        max_iterations=args.max_iter, verbose=not args.quiet,
        max_tokens=args.max_tokens,
    )
    success, result, meta = runner.run()
    if result:
        graphs = len(result.get("zone_graphs", []))
        nodes = len(result.get("nodes", []))
        minors = len(result.get("minor_objects", []) or [])
        print(f"\nResult: {'success' if success else 'partial success'}")
        print(f"   Zones: {graphs}, main-graph nodes: {nodes}, "
              f"minor sidecar: {minors}, iterations: {meta['iterations']}")
    return 0 if success else 1


if __name__ == "__main__":
    exit(main())
